app/src/main/java/com/babylon/wallet/android/presentation/account/settings/specificassets/SpecificAssetsDepositsScreen.kt
=> ABW-2370 Fix typo for empty state

app/src/main/java/com/babylon/wallet/android/WalletApp.kt, app/src/main/java/com/babylon/wallet/android/data/dapp/IncomingRequestRepository.kt, app/src/main/java/com/babylon/wallet/android/data/dapp/PeerdroidClient.kt, app/src/main/java/com/babylon/wallet/android/data/dapp/model/AccountsItem.kt, app/src/main/java/com/babylon/wallet/android/data/dapp/model/AuthRequestItem.kt, app/src/main/java/com/babylon/wallet/android/data/dapp/model/LedgerInteractionResponse.kt, app/src/main/java/com/babylon/wallet/android/data/dapp/model/WalletInteractionRequest.kt, app/src/main/java/com/babylon/wallet/android/data/transaction/DappRequestFailure.kt, app/src/main/java/com/babylon/wallet/android/domain/RadixWalletException.kt, app/src/main/java/com/babylon/wallet/android/domain/model/MessageFromDataChannel.kt, app/src/main/java/com/babylon/wallet/android/domain/usecases/BuildDappResponseUseCase.kt, app/src/main/java/com/babylon/wallet/android/presentation/main/MainViewModel.kt
Validate if challenge sent by dApp is 32byte hex value and display invalid request message if this situation happens. Without validation, passing arbitrary value as a challenge might crash dapp login flow
=> [ABW-2380] validate challenge in dapp authorized request

app/src/main/java/com/babylon/wallet/android/presentation/settings/appsettings/gateways/GatewaysViewModel.kt
a bug reported by Umair that keeps the button "add gateway" enabled although it shouldn't
=> Fix url text field validation

app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/depositguarantees/DepositGuaranteesViewModel.kt, app/src/test/java/com/babylon/wallet/android/presentation/settings/accountsecurity/DepositGuaranteesViewModelTest.kt
https://radixdlt.atlassian.net/browse/ABW-2445
Title explains it all.
Slack thread -> https://rdxworks.slack.com/archives/C031A0V1A1W/p1696887829708769?thread_ts=1696858782.099729&cid=C031A0V1A1W
=> ABW-2445 - Increase/decrease threshold changed from 0.1 to 1.

app/build.gradle, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/Thumbnail.kt, gradle/libraries.versions.toml
https://radixdlt.atlassian.net/browse/ABW-2367
https://github.com/radixdlt/babylon-wallet-android/assets/108684750/d03df5a3-4218-4afe-b65f-42303b415255
https://github.com/radixdlt/babylon-wallet-android/assets/108684750/960d26f8-865a-40e4-89c0-91098264a1a9
https://github.com/radixdlt/babylon-wallet-android/assets/108684750/705c55bd-66de-4364-ba51-320fcfc8c4a3
=> ABW-2367 - Gif support added.

app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/depositguarantees/DepositGuaranteesViewModel.kt
https://radixdlt.atlassian.net/browse/ABW-2459
I think title of the PR is self explanatory.
I could also filter out minus sign from the view but thought its better to do it in the view model.
Let me know your thoughts.
=> ABW-2459 - Do not allow negative numbers.

app/src/main/java/com/babylon/wallet/android/domain/model/Transferable.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/GeneralTransferAnalysis.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/TransactionTypeExtensions.kt
https://radixdlt.atlassian.net/browse/ABW-2491
Using Double instead of float for higher precision.
=> ABW-2491 - Float changed to Double to remain higher divisibility.

app/src/main/java/com/babylon/wallet/android/presentation/settings/appsettings/entityhiding/HiddenEntitiesScreen.kt
- updated spacing
- updated font style for hidden account/persona info
=> [ABW-2505] Update font style and spacing on hidden entities screen

app/src/main/java/com/babylon/wallet/android/data/transaction/DappRequestFailure.kt, app/src/main/java/com/babylon/wallet/android/domain/usecases/AuthorizeSpecifiedPersonaUseCase.kt, app/src/main/java/com/babylon/wallet/android/presentation/main/MainViewModel.kt, profile/src/main/java/rdx/works/profile/data/model/extensions/EntityExtensions.kt
- change type of exception returned when we can't automatically respond to dApp request
- update logic when hiding account
- show invalid persona error
=> ABW-2499 Don't remove reference to authorized persona when hiding account

app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/depositguarantees/DepositGuaranteesViewModel.kt
[[ticket_title](ticket_url)](https://radixdlt.atlassian.net/browse/ABW-2459)
Added a fix (previously only did for text field and forgot about button ) for incremental decrease of percentage for the deposit guarantee.
=> ABW-2359 - Do not allow for negative percentage for deposit guarantees.

docs/Conventions.md
This PR updates the Kotlin conventions based on the alignement meeting we had as a team.
=> Update Kotlin conventions

app/src/main/java/com/babylon/wallet/android/presentation/model/PersonaExtensions.kt
Quotations were added:
- on persona details screen
- on persona data selection screen in dapp request
=> [ABW-2529] Add quotation marks for a persona nickname if it is present

app/src/main/java/com/babylon/wallet/android/presentation/transfer/TargetAccountCard.kt, app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/transfer/prepare/PrepareManifestDelegate.kt, designsystem/src/main/java/com/babylon/wallet/android/designsystem/theme/RadixDimensions.kt, profile/src/main/java/rdx/works/profile/data/model/extensions/AccountExtensions.kt, profile/src/test/java/rdx/works/profile/accountextensions/TransferBetweenOwnedAccountsTest.kt
This PR updates the functionality to check when during a transfer between owned account a signature is required or not based on deposit rules of the `TO` (receiving) account.
In short, if the receiving account has deposit rules to deny deposits or any asset-exception deny rule, we should never prevent the transfer between owned accounts and in this case we should require a signature for it. Obviously when there are no deny rules the transfer does not require any signature.
This PR does not cover  the case when receiving account has "accept known" rule and the transferable asset is contained in the receiving account and we require signature (`deposit`) although we should not, for the reason that I explained [here](https://rdxworks.slack.com/archives/C03Q8QK1GLW/p1698788293923519?thread_ts=1 …
=> [ABW-2543] Check when signature is required when transfer between owned accounts based on deposit rules

app/src/main/java/com/babylon/wallet/android/presentation/settings/appsettings/linkedconnectors/LinkedConnectorsScreen.kt
Added button as a part of scrolling content.
Add more CE connections so that they push button out of the screen.
=> [ABW-2567] Add item to list content so it can be scrolled to

app/build.gradle
This PR solves / fixes / adds / includes functionality 1 and functionality 2.
1. Step 1
2. Step 2
3. Verify
```
```
```
```
Example:
```
```
paste link here
=> Bump version to 1.1.0

app/src/main/java/com/babylon/wallet/android/presentation/common/SeedPhraseInputDelegate.kt
Bug here is that I didn't keep indexes in state variable so validation was always passing
=> [ABW-2587] properly set mnemonic word indexes that will be validated

app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferViewModel.kt
This PR changes Max dialog functionality when remaining account is either 0 (0 amount Is applied straight away) or less than 1 xrd (fee amount) in which case we display slightly different dialog information the user that there will be not enough funds for the fee in this account.
1. Ideally see the video after reading above.
https://github.com/radixdlt/babylon-wallet-android/assets/108684750/e001b918-07cd-4dbb-8fd5-2440e20e6ade
=> ABW-2595 - Max amount button behaviour matched to whats on iOS. When less than 1xrd is applied we show different dialog.

app/build.gradle
=> Bump version to 1.2.0

app/src/main/java/com/babylon/wallet/android/data/gateway/extensions/StateEntityDetailsApiHelper.kt
Next pages need to request for explicit metadata optins
https://rdxworks.slack.com/archives/C03Q8QK1GLW/p1700737196445769?thread_ts=1700736753.091399&cid=C03Q8QK1GLW
=> Request explicit metadata for resources in all next pages

app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/seedphrases/confirm/ConfirmMnemonicScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/transfer/TargetAccountCard.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/card/PersonaCard.kt
This PR replace the hardcoded strings
=> Replace hardcoded strings

app/build.gradle
Version bump to 1.2.1
1. Step 1
2. Step 2
3. Verify
```
```
```
```
Example:
```
```
paste link here
=> Bump version to 1.2.1

app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsItem.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/AccountSecurityScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/depositguarantees/DepositGuaranteesScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/ledgerhardwarewallets/LedgerHardwareWalletsScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/appsettings/backup/BackupScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/appsettings/entityhiding/HiddenEntitiesScreen.kt
=> Update strings keys after crowdin cleanup

.github/workflows/publish_releases.yml, fastlane/Fastfile
This PR updates triggers of workflow
=> [DO-2094] update release workflow

app/src/main/java/com/babylon/wallet/android/presentation/account/recover/complete/RecoveryScanCompleteScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/withoutbackup/RestoreWithoutBackupScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/rootdetection/RootDetectionDialog.kt, app/src/main/java/com/babylon/wallet/android/presentation/status/signing/FactorSourceInteractionBottomDialog.kt
=> Update strigns after crowdin breaking changes

profile/src/main/java/rdx/works/profile/data/model/extensions/ProfileExtensions.kt, profile/src/main/java/rdx/works/profile/data/model/factorsources/DeviceFactorSource.kt, profile/src/main/java/rdx/works/profile/domain/GetFactorSourcesWithAccountsUseCase.kt, profile/src/main/java/rdx/works/profile/domain/GetProfileUseCase.kt
This change introduces change to filtering for babylon factor sources (seed phrase). Babylon should have excactly 24 words along with appropriate crypto parameters.
=> [ABW 2694] MARS factor source filtering

core/src/main/java/rdx/works/core/BigDecimalExtensions.kt, core/src/test/java/com/babylon/wallet/core/DisplayableQuantityTest.kt
Token formatting logic updated as per iOS.
More info see slack url in the ticket.
- Observe token amount is formatted properly especially when it comes to millions/billions/trillions etc.
=> ABW-2678 - Token formatting updated.

.github/workflows/publish_releases.yml
https://rdxworks.slack.com/archives/C03Q8QK1GLW/p1705587315631129
=> remove fetching of crashlytic secret

app/src/main/java/com/babylon/wallet/android/data/repository/cache/database/StateDatabase.kt, app/src/main/java/com/babylon/wallet/android/domain/SampleDataProvider.kt, app/src/main/java/com/babylon/wallet/android/domain/model/DApp.kt, app/src/main/java/com/babylon/wallet/android/domain/model/Transferable.kt, app/src/main/java/com/babylon/wallet/android/domain/model/resources/Resource.kt, app/src/main/java/com/babylon/wallet/android/domain/model/resources/metadata/StandardMetadata.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/GeneralTransferAnalysis.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/PoolContributionAnalysis.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/PoolRedemptionAnalysis.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/TransactionAnalysisDelegate.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/TransactionTypeExtensions.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/UnstakeAnalysis.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/PoolTypeContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/PoolsContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionAccountCard.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/WithdrawAccountContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/InvolvedComponentDetails.kt, config/schemas/com.babylon.wallet.android.data.repository.cache.database.StateDatabase/4.json, designsystem/src/main/res/drawable/ic_arrow_up_right.xml
This PR resolves dApp related to pools and displays them under "Contributing/Redeeming to pools" section. If dapp exist but it is not verified (dapp does not have link to pool component) - it is displayed as unknown pool.
1. Contribute to pool or reedem pool units
2. Validate that Pools section is populated - if you use sandbox dapp, you will see "1 pool component"
3. I'm not sure how to test this for a pool that has a reference to dapp, so I tested it by mocking this scenario.
=> [ADB-2674] Resolve dapps associated with pools

app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/TransactionAnalysisDelegate.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/TransactionTypeExtensions.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/UnstakeAnalysis.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/AccountDepositSettingsTypeContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionAccountCard.kt, app/src/test/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModelTest.kt, designsystem/src/main/res/drawable/ic_add_circle.xml, designsystem/src/main/res/drawable/ic_deposit_changes_heading.xml, designsystem/src/main/res/drawable/ic_minus_circle.xml
Changes to tx preview for account deposit settings:
- added icon to heading
- added icons for exception list changes
- display two sections - one for default deposit rule, and separate for asset exceptions. Previous iteration groups those changes together.
1. Test various deposit changes.
https://github.com/radixdlt/babylon-wallet-android/assets/118203440/b0785d50-27eb-405f-b386-e13d435b4481
=> [ABW-2677] Update account deposit settings change tx preview

.github/workflows/pr_and_main.yml, .github/workflows/publish_releases.yml
This PR fixed failing CI due to used untrusted actions.
=> [DO-000] update to trusted actions

.github/workflows/pr_and_main.yml, .github/workflows/publish_releases.yml
This PR fixes publish workflow.
=> [DO-000] fix publish workflow

app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/ValidatorStakeProcessor.kt
- calculation no longer depends on validator total stake and lsu total supply, uses only data available from manifest analysis
- validate that xrd stake worth is correct for STAKE transactions. 
- you can create manifest with multiple stake entries to multiple account by copying manifest sent to wallet by dashboard, copying it few times adjusting accounts/resource/validator addresses, to verify if aggregated worth values are also correct
=> Update calculation of xrd worth for LSUs

app/src/main/java/com/babylon/wallet/android/data/gateway/extensions/StateNonFungibleDetailsResponseItemExtensions.kt, app/src/main/java/com/babylon/wallet/android/utils/StringExtensions.kt
- added additional validation case that approve metadata as URL, suggestions welcomed
- create NFT collection with sandbox and check that NFT item with name "URL With white Space" is properly displayed now
=> [ABW-2915] Accept urls with spaces in last path segment as in NFT metadata

app/build.gradle
=> Bump version to 1.4.0

.github/workflows/publish_releases.yml
This PR fixes build and upload of Firebase Release App.
=> [DO-2207] fix firebase release app build

app/build.gradle, build.gradle, config/detekt.gradle, core/build.gradle, designsystem/build.gradle, gradle/libraries.versions.toml, gradle/wrapper/gradle-wrapper.properties, peerdroid/build.gradle, profile/build.gradle
- update kotlin compiler and AGP
- update few libs that felt safe to update
- move plugins and their versions into toml file
- migrate from kapt to ksp
1. Build the app and verify it works.
=> [ABW-2924] update kotlin compiler, few libs, move plugins into toml file

.github/workflows/release-drafter.yml
=> ci: grant permissions to release-drafter [DO-2224]

app/src/main/java/com/babylon/wallet/android/di/DataModule.kt, app/src/main/java/com/babylon/wallet/android/domain/model/assets/AccountWithAssets.kt, app/src/main/java/com/babylon/wallet/android/presentation/account/AccountScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/account/AccountViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/transfer/assets/AssetsChooserDelegate.kt, app/src/main/java/com/babylon/wallet/android/presentation/transfer/assets/ChooseAssetsSheet.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/AssetsView.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/AssetsViewData.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/NFTsTab.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/PoolUnitsTab.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/StakingTab.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/TokensTab.kt, app/src/main/java/com/babylon/wallet/android/presentation/wallet/AccountAssetsRow.kt
Consolidate data that are needed to display the assets view
=> Create assets view model

app/src/main/java/com/babylon/wallet/android/presentation/main/MainScreenNav.kt, app/src/main/java/com/babylon/wallet/android/presentation/survey/NPSSurveyDialog.kt, app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt
By mistake I removed dialog drag handle and X icon to close. This PR re-adds them and improves a bit launching dialog route
=> [ABW-3052] Add missing nps survey dialog header and improve dialog launching

app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/StakingTab.kt
It does exactly what it says on the tin
=> Update copy for staked validator item

app/src/main/java/com/babylon/wallet/android/domain/model/TransactionHistoryItem.kt, app/src/main/java/com/babylon/wallet/android/presentation/account/composable/TransactionHistoryItem.kt, app/src/main/java/com/babylon/wallet/android/presentation/survey/NPSSurveyDialogNav.kt
- make NPS survey high priority route
- remove complex transaction message for now
=> Make NPS high priority route and remove unknown transaction message

peerdroid/src/main/java/rdx/works/peerdroid/data/PeerdroidConnector.kt, peerdroid/src/main/java/rdx/works/peerdroid/data/PeerdroidLink.kt, peerdroid/src/main/java/rdx/works/peerdroid/data/webrtc/WebRtcManager.kt
This PR fixes two bugs that have been reported in crashlytics:
- the first issue `[base.apk] org.webrtc.DataChannel.unregisterObserver` and `Java_org_webrtc_DataChannel_nativeUnregisterObserver` that has been reported seems to be a WebRTC internal issue. I **assume** this has to do with **the way I terminate the WebRTC**. 
At the moment I close and unregister the peer connection and then the data channel. But with this way the data channel has been already closed. Although I could just leave the close/unregister of peer connection to terminate the data channel, I don't want to rely just on this, and I reordered the close/unregister of those two. So now the data channel gets closed and unregistered first, and then the peer connection.
- the next issue `UninitializedPropertyAccessException: …
=> Fix peer connection termination and initialization bug

app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/deriveaccounts/DeriveAccountsViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/derivepublickey/DerivePublicKeyViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/accountrecoveryscan/scan/AccountRecoveryScanScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/accountrecoveryscan/scan/AccountRecoveryScanViewModel.kt, app/src/main/java/com/babylon/wallet/android/utils/Constants.kt, profile/src/main/java/rdx/works/profile/data/repository/PublicKeyProvider.kt
- handle errors that can happen with accessing mnemonic in MARS
1. Setup wallet.
2. Add 2nd (non BDFS) seed phrase via MARS.
3. Change security settings on the device so that access to mnemonic is lost.
4. Restore BDFS (mandatory) and skip 2nd seed phrase restoration.
5. Try to do MARS with factor source that has no mnemonic restored.
=> Gracefully handle errors in MARS (no mnemonic)

app/src/main/java/com/babylon/wallet/android/data/repository/stream/StreamRepository.kt
- set `match_only_most_specific` to be always true
=> Update history request parameters

app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/DefaultSettingsItem.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/SwitchSettingsItem.kt
This PR fixes icon colors for the menu items on Settings screens
=> ABW-3126 - Account Settings - Icon colors

app/src/main/java/com/babylon/wallet/android/presentation/account/history/HistoryScreen.kt
=> Add navigation bars padding to filters sheet content

.github/actions/google-play-common/action.yaml, .github/workflows/pr_and_main.yml, .github/workflows/publish_releases.yml, .gitignore, app/build.gradle, app/proguard-rules.pro, app/src/main/java/com/babylon/wallet/android/RadixApplication.kt, gradle/libraries.versions.toml
This PR adds AppsFlyer SDK and sets up a secrets file configuration.
=> Integrate web referrals management SDK. Add secrets file configuration

app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/TroubleshootingSettingsViewModel.kt
=> [ABW-3202] Hide olympia import if not on mainnet

app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsItem.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/SecurityCenterScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/DefaultSettingsItem.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/SwitchSettingsItem.kt, app/src/main/res/values-en/strings.xml, designsystem/src/main/res/drawable/ic_developer_mode.xml, designsystem/src/main/res/drawable/ic_entity_hiding.xml
Copy updates, icon updates, font style and spacing. Related tickets:
https://radixdlt.atlassian.net/browse/ABW-3201
https://radixdlt.atlassian.net/browse/ABW-3203
https://radixdlt.atlassian.net/browse/ABW-3215
https://radixdlt.atlassian.net/browse/ABW-3216
https://radixdlt.atlassian.net/browse/ABW-3217
=> Minor ui tweaks to settings screens

app/src/main/java/com/babylon/wallet/android/domain/model/SecurityProblem.kt, app/src/main/java/com/babylon/wallet/android/domain/usecases/GetEntitiesWithSecurityPromptUseCase.kt, app/src/main/java/com/babylon/wallet/android/domain/usecases/GetSecurityProblemsUseCase.kt, app/src/main/java/com/babylon/wallet/android/presentation/account/history/HistoryViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsItem.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/SecurityCenterNav.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/SecurityCenterScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/SecurityCenterViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityfactors/SecurityFactorsScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/TroubleshootingSettingsScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/DefaultSettingsItem.kt, designsystem/src/main/java/com/babylon/wallet/android/designsystem/theme/RadixColors.kt, designsystem/src/main/java/com/babylon/wallet/android/designsystem/theme/Theme.kt
Security Center:
- added also warning on "Security Center" top level item when there are any issues detected.
- defined `SecurityProblem` class that now has 3 problems - seed phrase need backup or recovery & backup is not working
After backup work is done I think we should revisit backup related logic and define more granular backup issues if needed.
1. Check security center screen.
2. Verify that security problems warnings are displayed in top level security center item and on security center screen
=> [ABW-3165] Security center

app/src/main/java/com/babylon/wallet/android/data/repository/TransactionStatusClient.kt, app/src/main/java/com/babylon/wallet/android/domain/model/TransactionHistoryItem.kt, app/src/main/java/com/babylon/wallet/android/presentation/account/AccountViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/account/composable/TransactionHistoryItem.kt, app/src/main/java/com/babylon/wallet/android/presentation/account/history/HistoryViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/account/settings/AccountSettingsViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/actionableaddress/ActionableAddressView.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/TotalFiatBalanceView.kt, app/src/main/java/com/babylon/wallet/android/presentation/wallet/AccountCardView.kt, app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt, app/src/main/java/com/babylon/wallet/android/utils/AppEventBus.kt, app/src/test/java/com/babylon/wallet/android/presentation/WalletViewModelTest.kt, app/src/test/java/com/babylon/wallet/android/presentation/accountsettings/AccountSettingsViewModelTest.kt, config/detekt/detekt.yml, core/src/main/java/rdx/works/core/domain/assets/AssetPrice.kt
This PR improves wallet and account history screens UI performance by preventing heavy computation on the main thread.
=> Fix accounts and account history UI performance issues

app/src/main/java/com/babylon/wallet/android/domain/usecases/p2plink/ObserveAccountsAndSyncWithConnectorExtensionUseCase.kt, app/src/main/java/com/babylon/wallet/android/presentation/main/MainViewModel.kt, peerdroid/src/main/java/rdx/works/peerdroid/data/PeerdroidConnector.kt, profile/src/main/java/rdx/works/profile/datastore/EncryptedPreferencesManager.kt, profile/src/main/java/rdx/works/profile/domain/GetProfileUseCase.kt
This PR fixes the p2p links not being restored after wallet is deleted and a new profile is created.
=> Fix p2p links being lost after restoring a wallet

app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt
This PR prevents "re-link connectors" and the "new cloud backup system migration" pop-up screens from clashing at app startup. Also, this allows easily adding similar kinds of screens without worrying about the clashing and the order in which the screens are shown.
1. Install a build from 1.5.4 tag
2. Link a connector
3. Enable backups
4. Install a build from this branch (on top of the previous one)
5. Check that "Re-link Connectors" screen shows
6. Choose later or continue then go back to the wallet screen
7. Check that the new cloud backup system migration screen shows
8. Choose skip or log in to drive
9. Make sure the screens are no longer shown when reaching the wallet screen (after navigating through app, after backgrounding and resuming the app, after force closing and reopening the …
=> Pop-up screens queueing at app startup

app/src/main/java/com/babylon/wallet/android/presentation/navigation/NavigationHost.kt, app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/withoutbackup/RestoreWithoutBackupScreen.kt
[Jira ticket](https://radixdlt.atlassian.net/browse/ABW-3366)
This PR fixes clicking Ledger/Olympia only restore not directing users to main onboarding screen.
=> Fix user redirecting when clicking ledger/olympia only restore options

app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/accountrecoveryscan/scan/AccountRecoveryScanScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/ThrottleIconButton.kt, designsystem/src/main/java/com/babylon/wallet/android/designsystem/composable/RadixPrimaryButton.kt, designsystem/src/main/java/com/babylon/wallet/android/designsystem/composable/RadixSecondaryButton.kt, designsystem/src/main/java/com/babylon/wallet/android/designsystem/composable/RadixTextButton.kt, designsystem/src/main/java/com/babylon/wallet/android/designsystem/utils/ClickListenerUtils.kt
[Jira ticket](https://radixdlt.atlassian.net/browse/ABW-3375)
This PR fixes the deriving accounts sheet hanging when clicking scan more by adding 500ms throttling when clicking the button.
=> Fix deriving accounts sheet hanging when clicking scan more

app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonic/AddSingleMnemonicScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/seedphrases/SeedPhrasesScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/importlegacywallet/ImportLegacyWalletScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/WarningText.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/persona/RequiredPersonaInformationInfo.kt
[Jira ticket](https://radixdlt.atlassian.net/browse/ABW-3380)
This PR updates the position and color of warnings on the seed phrases screen.
=> Update position and color of warnings on seed phrases screen

app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsItem.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsViewModel.kt
[Jira ticket](https://radixdlt.atlassian.net/browse/ABW-3382)
This PR displays "Personas are not recoverable" security prompt under the Personas settings item when the backup is disabled or any personas are not recoverable.
=> [ABW-3382] - Not recoverable security prompt under Personas settings item

app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/PersonasScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/SecurityCenterScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/backup/BackupScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/ApplySecuritySettingsLabel.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/DefaultSettingsItem.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/SecurityPromptLabel.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/card/PersonaCard.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/modifier/ThrottleClickable.kt
- Updated Personas background, spacing, and security prompts style
- Updated style for security prompts on account cards
- Reused security prompt label composable
- Small UI improvements
=> Update Personas and account card prompts UI style

app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt
[Jira ticket](https://radixdlt.atlassian.net/browse/ABW-3393)
This PR fixes accounts total fiat value showing $0 while loading.
=> [ABW-3393] - Fix account total value showing 0 while loading

app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/importlegacywallet/ImportLegacyWalletViewModel.kt
[Jira ticket](https://radixdlt.atlassian.net/browse/ABW-3368)
This PR fixes the seed phrase screen not showing when importing olympia accounts that are already present but don't have the seed phrase entered.
1. Restore a profile containing olympia accounts
2. Skip seed phrase entering
3. Go to troubleshooting -> Import from a Legacy Wallet
4. Scan a QR with a few exported olympia accounts that are already present in the profile restored at step 1
5. Verify that the seed phrase entering screen is showing
=> [ABW-3368] Fix seed phrase screen not showing when importing legacy accounts

app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsViewModel.kt
- recover all seed phrases, even if there are none accounts on current network.
1. Follow jira [ticket](https://radixdlt.atlassian.net/browse/ABW-3394?atlOrigin=eyJpIjoiM2M1ZDgzMTFhNjljNDY0Mjk5ZDk3NjBhYTM4OTQ3ODkiLCJwIjoiaiJ9) for steps to reproduce
=> [ABW-3394] Always try to restore all seed phrases, regardless of accounts on current network

app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/seedphrases/SeedPhrasesScreen.kt
See details [here](https://radixdlt.atlassian.net/browse/ABW-3410).
=> [ABW-3410] Fix correct copy when 0 accounts connected to seed phrase in Seed Phrases screen

app/src/main/java/com/babylon/wallet/android/data/gateway/model/TokensAndLsusPricesResponse.kt
This PR fixes assets' worth computation when failing to convert a Double price to Decimal192 because of DecimalOverflow error.
=> [ABW-3408] - Fix fiat prices  decimal overflow parsing issue

app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/NFTsTab.kt
[Jira Ticket](https://radixdlt.atlassian.net/browse/ABW-3411)
This PR updates NFTs collection header to display the amount even if the entity details were not yet fetched. Displayed only the amount, because the total supply doesn't seem to be available before fetching the entity details.
=> [ABW-3411] Update NFTs collection header to display the amount

app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/SecurityCenterScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/SecurityCenterViewModel.kt
This PR improves the UI when opening Security Center screen by eliminating the temporary "all green" state and computing all the security problems on the background thread.
=> Improve UI when opening Security Center screen

app/src/main/java/com/babylon/wallet/android/data/repository/HttpHelpers.kt, app/src/main/java/com/babylon/wallet/android/domain/RadixWalletException.kt
[Jira ticket](https://radixdlt.atlassian.net/browse/ABW-3413)
This PR updates the error message when there is no network connection.
1. Enable airplane mode
2. Pull to refresh the wallet screen
3. Check the message
=> Add no network error message

app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsViewModel.kt
Please see this [thread](https://rdxworks.slack.com/archives/C03Q8QK1GLW/p1717592764981079) for a profile to test the issue.
1. Verify that after the change main seed phrase is displayed first
=> [ABW-3415] sort recoverable mnemonics to display main seed phrase first

app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/NFTsTab.kt
[Jira Ticket](https://radixdlt.atlassian.net/browse/ABW-3411)
This PR updates the NFTs amount label on the account screen to match iOS and to prevent inconsistencies between the initial state and the one when the NFT details were not yet fetched (by opening asset details).
[ABW-3411]: https://radixdlt.atlassian.net/browse/ABW-3411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3411] - Update NFTs amount displaying

profile/src/main/java/rdx/works/profile/domain/EnsureBabylonFactorSourceExistUseCase.kt
- when menmonic is missing and we add it via MARS, we should update exisitng factor source with that mnemonic
1. In missing mnemonic state, try to add that mnemonic via account recovery scan from settings. It should automatically be added and related accounts recovered.
2. Verify that adding new babylon seed phrase via MARS works as before.
3. Adding Olympia seed phrase is unchanged
=> [ABW-3419] Add mnemonic to existing factor source if it is missing (during MARS)

app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/TroubleshootingSettingsViewModel.kt
=> Fix when should show legacy wallet import

app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/backup/BackupScreen.kt
I missed this in the previous PR
=> Show label when backup disabled or not working

app/src/main/java/com/babylon/wallet/android/data/dapp/PeerdroidClient.kt, app/src/main/java/com/babylon/wallet/android/data/dapp/model/DappToWalletInteractionExtensions.kt, app/src/main/java/com/babylon/wallet/android/data/manifest/ManifestDataExtensions.kt, app/src/main/java/com/babylon/wallet/android/domain/model/deeplink/DeepLinkEvent.kt, app/src/main/java/com/babylon/wallet/android/domain/usecases/BuildDappResponseUseCase.kt, app/src/main/java/com/babylon/wallet/android/domain/usecases/RespondToIncomingRequestUseCase.kt, app/src/main/java/com/babylon/wallet/android/domain/usecases/deeplink/ProcessDeepLinkUseCase.kt, app/src/main/java/com/babylon/wallet/android/presentation/account/settings/devsettings/DevSettingsViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/account/settings/thirdpartydeposits/AccountThirdPartyDepositsViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/main/MainViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/mobileconnect/MobileConnectLinkViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/approveddapps/dappdetail/DappDetailViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/personadetail/PersonaDetailViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/PoolTypeContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/StakeTypeContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionPreviewHeader.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransferTypeContent.kt, app/src/test/java/com/babylon/wallet/android/data/dapp/DappToWalletInteractionUnvalidatedTest.kt, app/src/test/java/com/babylon/wallet/android/data/dapp/IncomingRequestRepositoryTest.kt, app/src/test/java/com/babylon/wallet/android/presentation/ChooseAccountsViewModelTest.kt, app/src/test/java/com/babylon/wallet/android/presentation/dapp/login/DAppAuthorizedLoginViewModelTest.kt, app/src/test/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModelTest.kt, app/src/test/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModelTestExperimental.kt
This PR updates the RCfM code based on the latest Sargon API changes.
=> RCfM api changes

app/src/main/java/com/babylon/wallet/android/data/dapp/IncomingRequestRepository.kt, app/src/main/java/com/babylon/wallet/android/data/gateway/serialisers/MetadataTypedValueSerializer.kt, app/src/main/java/com/babylon/wallet/android/domain/usecases/RespondToIncomingRequestUseCase.kt, app/src/main/java/com/babylon/wallet/android/presentation/mobileconnect/MobileConnectLinkScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/mobileconnect/MobileConnectLinkViewModel.kt
- spacing changes on the numbered list item
- make dapp name bold by using markdown in crowdin
=> [ABW-3468] Tweaks to mobile connect link UI

app/src/main/java/com/babylon/wallet/android/presentation/status/address/AddressDetailsDialog.kt, app/src/main/java/com/babylon/wallet/android/presentation/status/assets/fungible/FungibleDialogContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/status/assets/nonfungible/NonFungibleAssetDialogContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/status/assets/pool/PoolUnitDialogContent.kt, designsystem/src/main/res/drawable/ic_enlarge.xml
* Adds name metadata to token, lsu and pool unit dialog contents
* Fixes icons in address dialog in full address section
* Fixes typography in buttons in address dialog in full address section
=> UI fixes in asset dialog and address dialog

app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/AddLinkConnectorScreen.kt
[Jira Ticket](https://radixdlt.atlassian.net/browse/ABW-3577)
This PR fixes the link connector screen title copy.
=> Fix link new connector title copy

app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/deriveaccounts/DeriveAccountsDialog.kt, app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/derivepublickey/DerivePublicKeyDialog.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/approveddapps/ApprovedDappsScreen.kt
Now header of Approved Dapps Screen is Authorized Dapps
=> Update header to approved dApps

app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/accountonetime/OneTimeChooseAccountsViewModel.kt
[Jira Ticket](https://radixdlt.atlassian.net/browse/ABW-3608)
This PR adds the following functionality: If the dApp is asking for exactly(1) account and the user has only one account, pre-select it.
1. Send a request for exactly 1 account
2. Verify account is pre-selected
=> [ABW-3608] - Preselect account on login

app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/HomeCardsCarousel.kt
[Jira Ticket](https://radixdlt.atlassian.net/browse/ABW-3604)
This PR improves the home cards UI by fitting the title better when possible and fixes the text being cut off for enlarged fonts.
=> [ABW-3604] - Improve home cards UI

app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/importlegacywallet/ImportLegacyWalletScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/importlegacywallet/ImportLegacyWalletViewModel.kt
- first bug: importing mix of software & hardware accounts - only hardware ones were added to profile
- 2nd bug I found: when you import mix of accounts, and verify all hardware accounts, if you cancel biometrics prompt there is no way to complete the import by tapping continue.
=> [ABW-3639] Fix Olympia import issue

app/src/main/java/com/babylon/wallet/android/presentation/status/dapp/DAppDetailsDialogViewModel.kt
[Jira ticket](https://radixdlt.atlassian.net/browse/ABW-3648)
This PR removes the dApp website validation error.
=> [ABW-3648] - Fix dApp details error if unable to validate its website

app/src/main/java/com/babylon/wallet/android/presentation/mobileconnect/MobileConnectLinkScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/mobileconnect/MobileConnectLinkViewModel.kt
- use dappDefinition from metadata to load dApp details
1. Try to connect to radquest and verify name and icon show properly
=> Mobile connect - load dapp details based on request metadata

app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/SlideToSignButton.kt
[Jira ticket](https://radixdlt.atlassian.net/browse/ABW-3623)
This PR updates the slide to sign button to stay in its final position while the transaction is submitted.
1. Launch any transaction
2. Tap continue on the transaction review screen
3. Slide to end the "Slide to sign" button
4. Verify the slider to stay at its final position
5. Cancel the signing and verify the slider to be reset to its initial position
=> [ABW-3623] - Update slide to sign button

app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/backup/RestoreFromBackupViewModel.kt
This weird issue can only be reproduced by the development team locally and does not affect users. Branches that are merged with main and use the `sargon_os` sargon version and backup profiles with that version also include `securityStructuresOfFactorSourceIDs` in profile. This is not available in previous profiles so decoding fails. The problem here is that we allowed the code to continue instead of showing the error. This PR, uses `then` to pass the result of the method which saves the cloud backup locally and checks if the contents are valid.
=> Catch errors when saving cloud profile snapshot locally

app/src/main/java/com/babylon/wallet/android/presentation/account/AccountScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/personaedit/PersonaEditScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletScreen.kt, designsystem/src/main/java/com/babylon/wallet/android/designsystem/composable/RadixPrimaryButton.kt, designsystem/src/main/java/com/babylon/wallet/android/designsystem/composable/RadixSecondaryButton.kt
This PR fixes conflicting declarations in `RadixSecondaryButton.kt`
Also, updated the text style for both `RadixPrimaryButton` and `RadixSecondaryButton`.
=> Fix compile time issue & update buttons text style

app/src/main/java/com/babylon/wallet/android/presentation/settings/preferences/gateways/GatewaysScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/preferences/gateways/GatewaysViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferScreen.kt, app/src/test/java/com/babylon/wallet/android/presentation/settings/editgateway/GatewaysViewModelTest.kt
[Jira Ticket](https://radixdlt.atlassian.net/browse/ABW-3658)
- Fix bottom sheet dismissal after adding a new gateway
- Isolate the new gateway input fields into a separate data class within the state
- Remove unused code
=> [ABW-3658] - Fix gateways adding. Code clean up

app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/DappLoginAuthorizedNavGraph.kt, app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/DappLoginUnauthorizedNavGraph.kt, app/src/main/java/com/babylon/wallet/android/presentation/navigation/NavigationHost.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/createpersona/CreatePersonaConfirmationNav.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/createpersona/CreatePersonaConfirmationScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/createpersona/CreatePersonaNav.kt
Parameter is passed along persona creation flow, so that on confirmation screen we know the origin (settings or dapp request) and can display proper copy.
1. Create persona from settings/dapp request select persona screen
2. Verify that copies on the bottom CTA are correct -  "Continue to Persona List" / "Continue to Persona Selection"
=> [BW-3673] Add request source parameter in persona creation flow

app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/personadetail/PersonaDetailScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/RadixBottomBar.kt
[Jira Ticket](https://radixdlt.atlassian.net/browse/ABW-3665)
This PR updates "Hide This Persona" and "Edit Persona" buttons placement on Persona Details screen.
=> [ABW-3665] - Fix edit persona button placement

app/src/main/java/com/babylon/wallet/android/utils/BiometricExtensions.kt
This PR fixes unnecessary biometrics error logging.
=> Prevent biometrics error logging for specific error codes

app/src/main/java/com/babylon/wallet/android/presentation/account/settings/AccountSettingsViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/personadetail/PersonaDetailViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/preferences/WalletPreferencesScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/preferences/entityhiding/HiddenEntitiesScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/preferences/entityhiding/HiddenEntitiesViewModel.kt, app/src/test/java/com/babylon/wallet/android/presentation/accountsettings/AccountSettingsViewModelTest.kt, core/src/main/java/rdx/works/core/sargon/ProfileExtensions.kt, profile/src/main/java/rdx/works/profile/domain/ChangeEntityVisibilityUseCase.kt
- update entity hiding screen UI
- added previews for all ui state combinations
Note: Missing new strings as per zeplin screens. Before merging the PR strings will be added
1. Verify UI is updated according to zeplin designs linked in the [ticket](https://radixdlt.atlassian.net/browse/ABW-3554?atlOrigin=eyJpIjoiOGI1ODM2MjI0NGZmNGQxN2E2N2Q4OWVkYTNiZTI5MmUiLCJwIjoiaiJ9)
=> [ABW-3554] Update entity hiding screen

app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/FeesSheet.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/fees/TransactionFeesDelegate.kt
[Ticket](https://radixdlt.atlassian.net/browse/ABW-3741)
This PR fixes fee value updating from advanced customize fees screen
1. Select advanced mode in Customize Fees screen
2. Update fee padding or tip amount
3. Tap on Change fee payer 
4. Check that the fee value is reflected on fee payer selection sheet
=> [ABW-3741] - Fix fee value updating from advanced customize fees screen

app/src/main/java/com/babylon/wallet/android/presentation/navigation/NavigationHost.kt, app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferNav.kt, app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/transfer/assets/ChooseAssetsSheet.kt
It does what it says on the tin
=> [ABW-3785] Add info dialog click for choose assets sheet

app/src/main/java/com/babylon/wallet/android/AppLockStateProvider.kt, app/src/main/java/com/babylon/wallet/android/presentation/main/MainViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/preferences/WalletPreferencesScreen.kt, app/src/main/java/com/babylon/wallet/android/utils/ContextExtensions.kt
This PR:
- adds biometric check when switch on/off the advanced lock preference
- fixed the way the app is aware of its lock state (`AppLockStateProvider`)
Switch on/off the advanced lock and make sure that the lock screen applied properly
=> Add biometric check when switch advanced lock preference

app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/DappDetails.kt
Fix claim copy on dapp screen when toggling the switch
=> Fix claim copy

app/src/main/java/com/babylon/wallet/android/presentation/transaction/submit/TransactionSubmitDelegate.kt
Related [thread](https://rdxworks.slack.com/archives/C03Q8QK1GLW/p1729696104863219)
=> Fix tx submitting when there is no fee payer

app/src/main/java/com/babylon/wallet/android/presentation/transaction/fees/TransactionFees.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/fees/TransactionFeesDelegate.kt
[Ticket](https://radixdlt.atlassian.net/browse/ABW-3895)
This PR fixes the failing transaction when fee padding or tip percentage is edited.
=> [ABW-3895] - Fix tx failing because of fee computation

app/src/main/java/com/babylon/wallet/android/presentation/dialogs/assets/AssetDialog.kt, app/src/main/java/com/babylon/wallet/android/presentation/dialogs/assets/AssetDialogNav.kt, app/src/main/java/com/babylon/wallet/android/presentation/dialogs/assets/AssetDialogViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/dialogs/assets/lsu/LSUDialogContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/dialogs/assets/nonfungible/NonFungibleAssetDialogContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/navigation/NavigationHost.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsNavGraph.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewNav.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/summary/manifest/ManifestSummaryExtensions.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/CountedAmountSection.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/DepositAccountContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionAccountCard.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionTypeContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransferableLsuItemContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransferableNonFungibleItemContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransferablePoolUnitItemContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/WithdrawAccountContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/model/AccountWithTransferables.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/PoolUnitsTab.kt
This PR solves / fixes / adds / includes functionality 1 and functionality 2.
1. Step 1
2. Step 2
3. Verify
```
```
```
```
Example:
```
```
paste link here
=> NFT amounts

app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/summary/manifest/ManifestSummaryExtensions.kt
[ABW-3930](https://radixdlt.atlassian.net/browse/ABW-3930)
[Thread](https://rdxworks.slack.com/archives/C03Q8QK1GLW/p1731331814264089)
This PR fixes displaying accounts with no deposits in transaction review for a pre-auth transaction.
[ABW-3930]: https://radixdlt.atlassian.net/browse/ABW-3930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3930] - Fix pre-auth tx empty deposits

app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/summary/execution/ExecutionSummaryExtensions.kt
[Thread](https://rdxworks.slack.com/archives/C03Q8QK1GLW/p1731592377522389)
This PR fixes the amounts in the transaction review screen for the newly created resources. Also, this fixes the token creation transaction being rejected.
1. Launch a create token tx
2. Verify the amount to be shown as exact
3. Submit the transaction
=> Fix create token transaction

app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/summary/execution/GeneralTransferProcessor.kt
[Ticket](https://radixdlt.atlassian.net/browse/ABW-3474)
This PR fixes the issue of not showing the complex transaction preview when deploying a gumball machine for example.
1. Launch a Deploy gumball machine transaction
2. Check the transaction review shows the raw manifest and the complex transaction explanation dialog
=> [ABW-3474] - Fix complex transaction preview

profile/src/main/java/rdx/works/profile/data/repository/PublicKeyProvider.kt
This PR fixes the new derivation paths that will be created for personas. 
Error introduced by this PR https://github.com/radixdlt/babylon-wallet-android/pull/1042
Profiles that might have affected by this will be handled in sargon.
1. Create a new persona
2. Check the derivation path to be of identity kind
=> Fix identity derivation path when deriving keys

app/src/main/java/com/babylon/wallet/android/presentation/account/AccountScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/ongoingaccounts/OngoingAccountsScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/personaonetime/PersonaDataOnetimeScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/personaongoing/PersonaDataOngoingScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/selectpersona/SelectPersonaScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/personaonetime/OneTimeChoosePersonaScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/dialogs/dapp/DappInteractionDialogNav.kt, app/src/main/java/com/babylon/wallet/android/presentation/dialogs/preauthorization/PreAuthorizationStatusDialog.kt, app/src/main/java/com/babylon/wallet/android/presentation/dialogs/transaction/SuccessContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/approveddapps/dappdetail/DappDetailScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionExpirationInfo.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionPreviewHeader.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/ChooseAccountContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/ResolveDAppName.kt, app/src/main/java/com/babylon/wallet/android/presentation/wallet/AccountCardView.kt
[ABW-4005](https://radixdlt.atlassian.net/browse/ABW-4005)
This PR fixes the empty dApp name in the expiration area (at the bottom) for a pre-authorization transaction.
[ABW-4005]: https://radixdlt.atlassian.net/browse/ABW-4005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-4005] - Fix empty dApp name for pre-auth tx

app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginViewModel.kt
Show error dialog when proof of ownership is not valid.
Show snackbar for other ui related errors.
=> Fix error handling

app/src/main/java/com/babylon/wallet/android/presentation/transaction/submit/TransactionSubmitDelegate.kt
This PR fixes the crash when failing to respond to dApp with a signed subintent, for example if CE is not yet connected when re-opening the app from background.
=> [ABW-4008] - Fix crash when failing to respond with success subintent

app/build.gradle, app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/TroubleshootingSettingsScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/summary/execution/GeneralTransferProcessor.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/BoundedAmountSection.kt
- Updated unknown deposit message style
- Updated 'At Most' bounded amount handling
- Updated handling of transactions without any withdrawals/deposits
[Requirements](https://rdxworks.slack.com/archives/C031A0V1A1W/p1736173900669649)
[How to test & demo screenshots](https://rdxworks.slack.com/archives/C03Q8QK1GLW/p1736242494684059)
=> Hotfix 1.11.4

app/src/main/java/com/babylon/wallet/android/presentation/dialogs/assets/lsu/LSUDialogContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/dialogs/assets/pool/PoolUnitDialogContent.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/PoolUnitsTab.kt, core/src/main/java/rdx/works/core/domain/resources/Pool.kt
[Discussion](https://rdxworks.slack.com/archives/C03Q8QK1GLW/p1736351976693869?thread_ts=1736242494.684059&cid=C03Q8QK1GLW)
=> Display unknown amounts in pool unit and LSU asset details

app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionExpirationInfo.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionPreviewHeader.kt
When a dApp with a dApp definition unknown on ledger is received in dev mode, then the proposing dApp in transaction review's title should be called "Unknown dApp"
=> Unknown dApp name

app/src/main/java/com/babylon/wallet/android/domain/usecases/factorsources/GetFactorSourcesOfTypeUseCase.kt, app/src/main/java/com/babylon/wallet/android/presentation/account/createaccount/CreateAccountViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/common/PersonaEditable.kt, app/src/main/java/com/babylon/wallet/android/presentation/model/PersonaDisplayNameFieldWrapper.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityfactors/arculuscard/ArculusCardsViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityfactors/biometricspin/BiometricsPinScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityfactors/biometricspin/BiometricsPinViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityfactors/composables/FactorSourcesList.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityfactors/factorsourcedetails/FactorSourceDetailsViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityfactors/ledgerdevice/LedgerDevicesViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityfactors/offdevicemnemonic/OffDeviceMnemonicsViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityfactors/password/PasswordsViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/importlegacywallet/ImportLegacyWalletViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/RenameBottomSheet.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/card/SelectableFactorSourceCardView.kt, app/src/main/java/com/babylon/wallet/android/utils/Constants.kt, app/src/main/java/com/babylon/wallet/android/utils/SargonOsExtensions.kt, designsystem/src/main/java/com/babylon/wallet/android/designsystem/composable/MnemonicWordTextField.kt
This PR solves adds functionality to change the default device factor source in Biometrics/PIN screen.
1. You need to have multiple device factor sources (restore wallet and skip seed phrases)
=> [ABW-4050] Change main device factor source

app/build.gradle, app/src/main/java/com/babylon/wallet/android/domain/CommonExceptionMessage.kt, app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/derivepublickeys/DerivePublicKeysDialog.kt, app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/signatures/GetSignaturesDialog.kt, app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/spotcheck/SpotCheckDialog.kt, app/src/main/java/com/babylon/wallet/android/presentation/addfactorsource/device/seedphrase/DeviceSeedPhraseScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/addfactorsource/name/SetFactorSourceNameScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/common/UiMessage.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/linkedconnectors/AddLinkConnectorViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/transaction/model/TransactionErrorMessage.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/AddLinkConnectorScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/Dialogs.kt, app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/RadixSnackbarHost.kt
* Adds ability for users to report sargon messages via email.
=> Release 1.12.4

app/build.gradle
=> Release 1.15.0

app/src/main/java/com/babylon/wallet/android/presentation/addfactorsource/kind/AddFactorSourceKindScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonic/ImportSingleMnemonicScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/ImportMnemonicsScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/selectfactorsource/SelectFactorSourceScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityfactors/biometricspin/BiometricsPinNav.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityfactors/biometricspin/BiometricsPinScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityfactors/biometricspin/BiometricsPinViewModel.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityfactors/biometricspin/seedphrase/reveal/RevealSeedPhraseNav.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityfactors/biometricspin/seedphrase/reveal/RevealSeedPhraseScreen.kt, app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityfactors/biometricspin/seedphrase/reveal/RevealSeedPhraseViewModel.kt
- Fixed `FactorSourceCardView` displaying in dark mode
- Fixed crash when tapping on 'write down seed phrase' security problem
=> Fix issues
