radixdlt/babylon-wallet-android

app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/AccountDepositSettingsAnalysis.kt

If only deposit change done was change to depositor list, it was not properly rendered on the transaction review, although the manifest for the actual change (if you approve transaction) is correct

[ABW-2384] fix bug in depositor changes rendering on transaction preview

---

app/src/main/java/com/babylon/wallet/android/presentation/transfer/prepare/PrepareManifestDelegate.kt

https://radixdlt.atlassian.net/browse/ABW-2359
The issue here was that logic for whether mnemonicHasBeenImported was wrong.
The logic there should be the same as we use for display "Please Recover your account" on the account card on the home view.
If we cannot find mnemonic it means account does not need recovery and in this case we should use deposit instruction not try_deposit_or_abort.
IOS logic once again for comparison, please focus on ** userHasAccessToMnemonic** part -> https://github.com/radixdlt/babylon-wallet-ios/pull/800/files
Please test transfer from Software account to Ledger account and vice versa. Both flows should trigger ledger signing request .

ABW-2359 - Deposit instruction fix

---

app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsViewModel.kt
profile/src/main/java/rdx/works/profile/domain/backup/RestoreProfileFromBackupUseCase.kt

- since we always have mainnet in `.preset` that we set in profile init, we just need to change gateway on the profile object just before restoring. Done this changeGateway call in 2 places - actual backup restoring use case and when loading profile in restore mnemonic screen, so that we show list of mainnet accounts instead of accounts on a network that was set to default at the moment of doing backup

Change gateway to mainnet after restoring backup

---

app/build.gradle
app/src/main/java/com/babylon/wallet/android/presentation/settings/appsettings/gateways/GatewaysScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/appsettings/gateways/GatewaysViewModel.kt
app/src/main/java/com/babylon/wallet/android/utils/StringExtensions.kt
app/src/test/java/com/babylon/wallet/android/presentation/settings/editgateway/GatewaysViewModelTest.kt
app/src/test/java/com/babylon/wallet/android/utils/SanitizeAndValidateGatewayUrlTest.kt
gradle/libraries.versions.toml

[Gateway settings: support HTTP:PORT on dev mode](https://radixdlt.atlassian.net/browse/ABW-2336)
This PR adds logic when adding a new gateway url:
If developer mode is enabled almost any url is accepted, but with developer mode disabled we allow only https url.
Current implementation fails only when trying to add an IPv6. See the comments for more details.
Due to Android version compatibility we can't use other APIs because either they require minsdk 29 or 34.

[ABW-2336] Add gateway url based on developer mode

---

app/src/main/java/com/babylon/wallet/android/presentation/transaction/fees/TransactionFees.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/fees/TransactionFeesDelegate.kt

https://radixdlt.atlassian.net/browse/ABW-2398
https://github.com/radixdlt/babylon-wallet-android/assets/108684750/d53e9afc-d6fd-4efb-843b-57b0f7c7ce2a
Tip percentage field cannot accept decimals, only whole numbers (integers)

ABW-2398 - Tip not accepting decimals, only whole numbers.

---

app/src/main/java/com/babylon/wallet/android/data/dapp/IncomingRequestRepository.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/InitialAuthorizedLoginRoute.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/DappLoginAuthorizedNavGraph.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/account/ChooseAccountsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/permission/LoginPermissionScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/personaongoing/PersonaDataOngoingScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/selectpersona/SelectPersonaNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/selectpersona/SelectPersonaScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/selectpersona/SelectPersonaViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/accountonetime/OneTimeChooseAccountsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/login/DAppUnauthorizedLoginScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/login/DAppUnauthorizedLoginViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/personaonetime/PersonaDataOnetimeScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/transaction/TransactionStatusDialogViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/TransactionAnalysisDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/submit/TransactionSubmitDelegate.kt
app/src/test/java/com/babylon/wallet/android/presentation/dapp/selectpersona/SelectPersonaViewModelTest.kt
core/src/main/java/rdx/works/core/EncryptionHelper.kt

- allow IncomingRequestRepository to return null for requests
- every view model that uses requests (dapp login flows and transaction review) is now checking up front if requests is not null, and if it is null, we break handling the flow
Crash was happening when user left app on dapp login flow/transaction review, system killed app, user reopened app from recent apps and view model accessed requests, which were no longer there since IncomingRequestRepository was recreated. 
Land on any dapp login flow or transaction review, background the app, kill process via Logcat/right click/kill process, and then try to re-open app from recent. Before this change, in every flow (authorized/unauthorized login and transaction review) app will crash.

ABW-2380 request crashes

---

app/src/main/java/com/babylon/wallet/android/data/dapp/LedgerMessenger.kt
app/src/main/java/com/babylon/wallet/android/data/dapp/PeerdroidClient.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/createaccount/withledger/CreateAccountWithLedgerScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/createaccount/withledger/CreateAccountWithLedgerViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/importlegacywallet/ImportLegacyWalletScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/importlegacywallet/ImportLegacyWalletViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/ledgerhardwarewallets/AddLedgerDeviceViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/ledgerhardwarewallets/LedgerHardwareWalletsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/ledgerhardwarewallets/LedgerHardwareWalletsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/appsettings/linkedconnectors/AddLinkConnectorViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/appsettings/linkedconnectors/LinkedConnectorsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/appsettings/linkedconnectors/LinkedConnectorsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/AddLedgerDeviceScreen.kt
app/src/test/java/com/babylon/wallet/android/presentation/createaccount/withledger/AddLedgerDeviceViewModelTest.kt
app/src/test/java/com/babylon/wallet/android/presentation/createaccount/withledger/CreateAccountWithLedgerViewModelTest.kt
peerdroid/src/main/java/rdx/works/peerdroid/data/PeerdroidConnector.kt
profile/src/main/java/rdx/works/profile/domain/GetProfileUseCase.kt

- added possibility to check if are connected to any CE
- changed generic error for ledger request 
- used connection state in ledger flows to display link connector screen when we disconnect CE in browser
- adding ledger in create account/settings/olympia import.
- ledger flow is implemented a bit differently in olympia import compared to create account/settings, so please be aware of that.
- after linking ledger in any flow, please disconnect in browser, and verify if we are asked to link again when adding/trying to use ledger device again

[ABW-2406] Detect no CE connection in add ledger flow

---

app/src/main/java/com/babylon/wallet/android/data/manifest/ManifestExtensions.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/submit/TransactionSubmitDelegate.kt

https://radixdlt.atlassian.net/browse/ABW-2424
Where sending transaction that involves multiple assertions the app did not increase index for the subsequent insertions.
So right now it is fixed the same way as IOS has done.
Steps to test on Stokenet:
1. Send the following manifest (with your accounts etc):
```
CALL_METHOD
Address("account_tdx_2_12yr3w52llr4gz8jfwxrd4rhwwpd3fsv9uz69uucfr96n43hp79fwtr")
"withdraw"
Address("resource_tdx_2_1tknxxxxxxxxxradxrdxxxxxxxxx009923554798xxxxxxxxxtfd2jc")
Decimal("4")
;
TAKE_FROM_WORKTOP
Address("resource_tdx_2_1tknxxxxxxxxxradxrdxxxxxxxxx009923554798xxxxxxxxxtfd2jc")
Decimal("2")
Bucket("bucket1")
;
CALL_METHOD
Address("component_tdx_2_1cqm76npjd0y87grsvt0cpplqw25atu9934d7rgraejf895el9x0zkm")
"buy_gumball"
Bucket("bucket1")
;
CALL_METHOD …
```

ABW-2424 - Guarantee index increased for multiple assertions.

---

app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/importlegacywallet/ImportLegacyWalletScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/importlegacywallet/ImportLegacyWalletViewModel.kt
app/src/main/res/values-en/strings.xml

- warning dialog
- enable "Import" button only if seed phrase form is filled

Olympia import seed phrase warning

---

app/src/main/java/com/babylon/wallet/android/data/dapp/PeerdroidClient.kt
app/src/main/java/com/babylon/wallet/android/presentation/main/MainViewModel.kt
peerdroid/src/main/java/rdx/works/peerdroid/data/PeerdroidConnector.kt
peerdroid/src/main/java/rdx/works/peerdroid/data/PeerdroidLink.kt
profile/src/main/java/rdx/works/profile/domain/GetProfileUseCase.kt

[Android | 1.0.0 #9 | P2P - Linked Connector - Issue post-restore of backup](https://radixdlt.atlassian.net/browse/ABW-2299)
When the user deletes the profile, we call the `peerdroidClient.terminate()`  in the `onDeleteWalletConfirm()` of the `BackupViewModel`. Then:
1. the app navigates to the onboarding screen
2. user clicks on restore profile and when restore is done the app navigates to the wallet screen
3. `observeP2PLinksflow` won't work there, and we need to restart the app in order to make it work.
The cause was the `distinctUntilChanged` at `GetProfileUseCase.p2pLinks`. This property would prevent the subsequent repetitions of the same value every time the profile gets updated and thus would prevent the call of the `establishLinkConnection` in the `MainViewModel`. 
I removed the …

[ABW-2299] Keep listening for p2plinks after restore

---

app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/depositguarantees/DepositGuaranteesScreen.kt

https://radixdlt.atlassian.net/browse/ABW-2460
Ime action was replaced with Done, because previously we were adding new line character on click event which was breaking the functionality.

ABW-2460 - None button replaced with Done.

---

profile/src/main/java/rdx/works/profile/data/model/apppreferences/Gateways.kt
profile/src/test/java/rdx/works/profile/gateways/ExtensionsTest.kt

[Fix the way we verify the gateway change](https://radixdlt.atlassian.net/browse/ABW-2483)
The first versions (1.0.0 - 1.0.2) of the Android wallet contained the mainnet gateway with wrong name property. So users who export a profile from these versions and import to the latest versions cause a crash in the app. See more details in the ticket.
The unit test explains better the fix.

[ABW-2483] Fix how to check if a gateway is already in saved gateways

---

app/src/main/java/com/babylon/wallet/android/presentation/model/ActionableAddress.kt

[Validator addresses do not redirect to the correct page on Radix Dashboard](https://radixdlt.atlassian.net/browse/ABW-2478)
The validator addresses must resolve to "dashboard_url"/ **component**/validator_rdx1...

[ABW-2478] Update ActionableAddress to support url for validators

---

app/src/main/java/com/babylon/wallet/android/WalletApp.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/BuildDappResponseUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/account/ChooseAccountsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/personaonetime/PersonaDataOnetimeScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/personaongoing/PersonaDataOngoingScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/accountonetime/OneTimeChooseAccountsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/login/DAppUnauthorizedLoginViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/submit/TransactionSubmitDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/Dialogs.kt

- trhow no menmonic exception whenever there is no mnemonic during signing
- handle it on the UI for dapp login and transaction review
- strings added in crowdin, waiting for propagation
- to test: create wallet with at least 1 olympia software account, back it up. Then uninstall wallet, restore backup and don't recover olympia seed phrase. Now you can get this error either by doing a transaction which involves that Olympia account signature, or send dapp request with proof of accounts  and select that olympia account.

ABW-2466 Throw no mnemonic exception and handle it on UI

---

app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/TransactionAnalysisDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/NetworkFeeContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionPreviewHeader.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionPreviewTypeContent.kt

…view screen to speed up loading process.
https://radixdlt.atlassian.net/browse/ABW-2473
https://github.com/radixdlt/babylon-wallet-android/assets/108684750/588934c2-a659-4df0-af9f-519b1afa1387
I added shimmer instead of loading as mentioned in the ticket as I think its nicer and will be consistent with behaviour we have in the AssetRow.

ABW-2473 - Fee and the payer are being determined while being on Tx Review screen

---

app/src/main/java/com/babylon/wallet/android/presentation/account/AccountScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/ThrottleIconButton.kt

Updating [compose dependencies](https://github.com/radixdlt/babylon-wallet-android/pull/596) will fix this issue. Keeping it open until we merge dependency updates.
- added IconButton with throttle click capability until we update Compose/Navigation

[ABW-2504] Fix crash when opening account settings

---

app/src/main/java/com/babylon/wallet/android/presentation/common/ViewModelDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/TransactionAnalysisDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/fees/TransactionFeesDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/guarantees/TransactionGuaranteesDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/submit/TransactionSubmitDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/accounts/AccountsChooserDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/assets/AssetsChooserDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/prepare/PrepareManifestDelegate.kt
app/src/test/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModelTest.kt
app/src/test/java/com/babylon/wallet/android/presentation/transfer/TransferViewModelTest.kt

This PR is a showcase for how we can (slightly) improve the way we create delegates in the viewmodel.
The goal is: 
- to reduce the amount of the constructor parameters in the viewmodels
- to inject the required parameters in the delagates
If we want to go further, we can make an interface with the attributes and functions that we want to delegate, and then the viewmodel can implement that interface by delegating the implementation.

[ABW-2528] Improve viewmodel delegates

---

app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/seedphrases/SeedPhrasesScreen.kt

Change UI of seed phrase card when restoration is needed.

[ABW-2540] Change display of seed phrase card when seed phrase is missing

---

app/src/main/java/com/babylon/wallet/android/domain/usecases/AuthorizeSpecifiedPersonaUseCase.kt

This side effect was introduced by exception refactor. When request can't be handled automatically, and we want to trigger dapp request handling flow, we should return specific exception to indicate that.
Detailed step by step instruction how to reproduce can be found in linked ABW-2530 Jira ticket.

[ABW-2530] return proper exception when request can't be handled automatically

---

app/src/main/java/com/babylon/wallet/android/domain/usecases/AuthorizeSpecifiedPersonaUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/InitialAuthorizedLoginRoute.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/DappLoginAuthorizedNavGraph.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/selectpersona/SelectPersonaScreen.kt

Before this change, if we granted access to accounts and (or) persona data, for example exactly 2 accounts, and fired same request again, but with proof of ownership, app would crash because we wanted to handle that request entirely in the background, without any UI, and we didn't prompt for biometrics.
After the fix in this scenario we trigger dapp login flow where we immediately prompt for biometrics, if granted we show signing sheet, and if signatures are successfull, we immediately complete request.
If mnemonic for account is missing, we display same dialog as in other places.
1. Trigger ongoing request for accounts, complete the flow
2. Now trigger same request but check with proof in Sandbox dapp
3. Verify that handling is as described above. …

[ABW-2535] handle requests that need signature and were already granted

---

app/src/main/java/com/babylon/wallet/android/presentation/main/MainViewModel.kt

Before we added error dialogs for those scenarios, request handling reached Dapp login flow screen, where request was marked as handled in the queue. Since now failure is handled in main view model, is should also be marked as handled there,
See detailed steps in Jira ticket.

[ABW-2549] If request can't be handled due to failure, remove it from queue

---

app/src/main/java/com/babylon/wallet/android/presentation/model/ActionableAddress.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/transaction/TransactionStatusDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/ActionableAddressView.kt
app/src/test/java/com/babylon/wallet/android/presentation/model/AddressDashboardUrlTest.kt
core/src/main/java/rdx/works/core/AddressValidator.kt
profile/src/main/java/rdx/works/profile/data/model/apppreferences/Radix.kt

This PR fixes a problem when user is navigated to Mainnet dashboard after successfully tx, even when being on different network.
Given tx is successful, when View on Radix dashboard clicked, verify that user is navigated to correct dashboard associated with current networkID, not always to main net dashboard

ABW-2534 - Dashboard url determined based on networkId.

---

app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/GeneralTransferAnalysis.kt
app/src/test/java/com/babylon/wallet/android/presentation/transaction/GeneralTransactionAnalysisTest.kt

Ticket -> https://radixdlt.atlassian.net/browse/ABW-1975
So far order of the depositing accounts was inherited from RET **accountDeposits**  which does not take into the account any order whatsoever.
This change is to keep the order of the Depositing accounts in the Tx Review in the same way as in the wallet dashboard.
1. Go to https://radix-dapp-toolkit-dev.rdx-works-main.extratools.works/integration-tests
2. Run Gumball machine example 1
3. Verify that depositing accounts are show in the same order as in the dashboard.

ABW-1975 - Depositing accounts are ordered in the same way as in the wallet dashboard

---

app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/account/ChooseAccountsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/personaonetime/PersonaDataOnetimeScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/personaongoing/PersonaDataOngoingScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/selectpersona/SelectPersonaScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/seedphrases/reveal/RevealSeedPhraseScreen.kt

No mnemonic exception was passed as a `cause` of signature failure, so error handling flow in dapp login was wrong in this scenario.
Please refer to Jira ticket, there are detailed steps to reproduce.

[ABW-2554] update exception handling to properly show no mnemonic error

---

app/src/main/java/com/babylon/wallet/android/presentation/account/settings/AccountSettingsViewModel.kt

Settings section are not data classes, so `distinct()` did not work and we need to explicitly check if dev section exist before adding it
1. Edit account label and see dev section duplicated

[ABW-2555] Fix showing duplicate dev section

---

app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/TransactionAnalysisDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/submit/TransactionSubmitDelegate.kt
app/src/test/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModelTest.kt

After the [update of the delegates in viewmodel](https://github.com/radixdlt/babylon-wallet-android/pull/599) the delegates of the `TransactionReviewViewModel` get a different instance of the `TransactionClient` which breaks the logic of the viewmodel (requires same instance of client in delegates) and as a result the signing bottom sheet dialog is not shown.
This is definitely not the best solution but with the refactor of signing process most probably the `TransactionClient` won't exist at all or not in the form it is now. So imo this should be a fine solution at the moment.
I also checked the other constructor parameters of the delegates and didn't see any consequences. Most of them are usecases which take the same Singleton repository.
1. Make any transaction 
2. Verify that you see …

[ABW-2561] Pass same instance of TransactionClient in delegates of TransactionReviewViewModel

---

app/src/main/java/com/babylon/wallet/android/data/repository/TransactionStatusClient.kt
app/src/main/java/com/babylon/wallet/android/data/transaction/TransactionClient.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/GetFreeXrdUseCase.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/transaction/PollTransactionStatusUseCase.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/transaction/SubmitTransactionUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/submit/TransactionSubmitDelegate.kt
app/src/test/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModelTest.kt

With the previous implementation I have used current epoch directly from Tx submission GW call however we need one from Poll transaction status GW call.
1. Simulate Transaction rejection (**temporarilyRejected**) and verify that tx processing time is passed along and displayed properly.

ABW-2550 - Transaction processing time displayed properly for rejected transaction

---

app/src/main/java/com/babylon/wallet/android/domain/model/resources/Resource.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/composable/FungibleTokenBottomSheetDetails.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/composable/LSUBottomSheetDetails.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/composable/PoolUnitBottomSheetDetails.kt
app/src/test/java/com/babylon/wallet/android/domain/model/ResourceTests.kt

This PR hides behaviours section for XRD resource. For any other resources there is no difference, functionality stays the same.
1. Go to XRD and verify that there is no behaviours section.
https://github.com/radixdlt/babylon-wallet-android/assets/108684750/d12a3867-bafb-4b37-9fd3-726a1cf47f9b
- [] I have checked XRD resource details page to see if behaviours section is gone
- [] I have written unit tests

ABW-2551 - Behaviours section hidden for XRD resource.

---

app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferViewModel.kt

This PR adds a dialog when clicking Max amount on Transfer page to determine if we want to leave 1 xrd for the fee or transfer the whole amount (empty account).
Only applies to XRD fungible.
1. Initiate XRD transfer
2. In the field, hit Max button and chose one of the options.
3. If empty account chosen, verify that Insufficient balance error is displayed and another account has to be choose to pay for the fee in order to complete the transfer.

ABW-2498 - When max clicked, dialogs show to confirm which amount we want to insert.

---

app/src/main/java/com/babylon/wallet/android/presentation/common/SeedPhraseInputDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/navigation/NavigationHost.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/AccountSecurityNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/seedphrases/confirm/ConfirmMnemonicNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/seedphrases/confirm/ConfirmMnemonicScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/seedphrases/confirm/ConfirmMnemonicViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/seedphrases/reveal/RevealSeedPhraseNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/seedphrases/reveal/RevealSeedPhraseScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/seedphrases/reveal/RevealSeedPhraseViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/SeedPhraseInputForm.kt
designsystem/src/main/java/com/babylon/wallet/android/designsystem/composable/MnemonicWordTextField.kt
profile/src/main/java/rdx/works/profile/data/model/MnemonicWithPassphrase.kt
profile/src/main/java/rdx/works/profile/domain/GetProfileUseCase.kt

This PR adds verification step after user confirm he/she backed up her seed phrase on Reveal Seed phrase screen. User is asked to fill in random 4 words of mnemonic, and those words are compared with corresponding words from mnemonic stored on device.
1. Create account and transfer some XRD into it, for a seed phrase that was not yet backed up.
2. Tap prompt to back up mnemonic on account card or account details and reveal seed phrase.
3. When closing, confirm you written down the phrase.
4. Pass additional verification.
https://github.com/radixdlt/babylon-wallet-android/assets/118203440/9b73871b-cf98-4901-b1fe-f633eebd7b8d

[Abw-2454] Verify user written seed phrase

---

app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsViewModel.kt
profile/src/main/java/rdx/works/profile/data/model/factorsources/FactorSource.kt
profile/src/main/java/rdx/works/profile/data/model/pernetwork/FactorInstance.kt
profile/src/main/java/rdx/works/profile/domain/backup/RestoreMnemonicUseCase.kt
profile/src/main/java/rdx/works/profile/olympiaimport/OlympiaWalletDataParser.kt
profile/src/test/java/rdx/works/profile/domain/account/MigrateOlympiaAccountsUseCaseTest.kt
profile/src/test/java/rdx/works/profile/snapshot/SnapshotEncodingTests.kt

Condition we used to check if user entered correct mnemonic when restoring profile from backup was only executed when user had at least 1 software account. Tying it with accounts is not necessary.
I also simplified mnemonic input validation.
1. Create new profile, 1st account with ledger, no software accounts.
2. Back up the profile and write down seed phrase.
3. Delete wallet and try to restore from backup by entering seed phrase - it's not posible to go past menmonic input and trigger mnemonic validation check

[ABW-2577] Fix backup recovery for profile with no babylon software accounts

---

core/src/main/java/rdx/works/core/BigDecimalExtensions.kt

For values below 1 we didn't use same decimal format as for any other amount.
1. You need to own token with amount less then 1 to se wrong display.

[ABW-2604] Fix formatting for amounts below 1

---

app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsViewModel.kt
profile/src/main/java/rdx/works/profile/data/model/Profile.kt
profile/src/main/java/rdx/works/profile/domain/CheckMnemonicIntegrityUseCase.kt

Right now, if you skip babylon seed recovery, there is new BDFS that will be marked as main. If user will remove security settings of device and we lose encryption key to decrypt mnemonics, we delete them and expect recovery of main one (used for account/persona creation - otherwise app will crash if we try to create new entity). But the logic for detecting main one was not updated in BDFS skip changes, so we would restore wrong one (not used for entity creation)
1. Restore app from backup, skip BDFS recovery
2. Remove device security screen and addd it again
3. Open app - you will see mandatory recovery that is now skippable - also a bug.
4a. Enter seed phrase, try to create account/persona - app crashes.
4b. Skip recovery - we have wallet without main BDFS mnemonic.
This PR aims to fix …

[ABW-2609] Update detection of main babylon seed phrase recovery 

---

app/src/main/java/com/babylon/wallet/android/data/repository/state/StateRepository.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/AccountViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/assets/AssetsChooserDelegate.kt
app/src/test/java/com/babylon/wallet/android/domain/usecases/SearchFeePayersUseCaseTest.kt

The account and choose assets screens are being updated when an account's resources change in db.
Lets say that `Account A` and `Account B` both have stakes to the same validator `Validator 1`. If the user navigates to the `Account A` and expands the `Validator 1` the details will shimmer and then fetched from the stream when db updates itself.
Now if we navigate to `Account B` which holds stake to the same validator, we have already cached the validator's details, but we need to find if there are specific NFT claims to this account <-> validator pair. If yes, we do update the db when expanding the stakes section, BUT the db will not fire an update because the basic QUERY that is firing is not taking into account owned NFTs.
The solution is to just return the result, instead of simply …

Return the currently newly resolved validators with stakes

---

app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsViewModel.kt
profile/src/main/java/rdx/works/profile/data/model/Profile.kt

This PR fixes a problem when we show biometric (and create BDFS when we shouldn't i.e. when clicking Seed phrase required on the card and start restoration process)
See video.
1. Finish restoration some BDFS accounts with skipping seed phrases for them.
2. Once you have them click on **Seed phrase required - begin entry** button and make sure that no biometric is shown as no BDFS should be created.
https://github.com/radixdlt/babylon-wallet-android/assets/108684750/f143a158-51a9-410c-88a4-ea210eadea75

ABW-2605 - Biometric auth only asked when we need it and when BDFS is  created.

---

app/src/main/java/com/babylon/wallet/android/WalletApp.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/AccountScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/main/MainScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/main/MainScreenNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/navigation/NavigationHost.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/AccountSecurityNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/seedphrases/SeedPhrasesNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/seedphrases/SeedPhrasesScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletScreen.kt

This PR refactores RestoreMnemonicsArgs to contain only RestoreProfile and remove RestoreMnemonic:
Also moved Skip button at the bottom of the page during Seed Phrase Restoration, see the ticket or here -> https://rdxworks.slack.com/archives/C03QFAWBRNX/p1700727176253209?thread_ts=1700663158.113269&cid=C03QFAWBRNX
1. Go through seedphrase restoration and verify behaviour have not changed except:
Skip button appears at the bottom of the page. See screenshots.

ABW-2614 - Skip button moved to the bottom of the page. Refactored RestoreMnemonicsArgs to contain only RestoreProfile case.

---

app/src/main/java/com/babylon/wallet/android/data/dapp/LedgerMessenger.kt
app/src/main/java/com/babylon/wallet/android/domain/RadixWalletException.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/transaction/CollectSignersSignaturesUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/DappInteractionFailureDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/FailureDialogState.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/DappLoginAuthorizedNavGraph.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/account/ChooseAccountsNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/account/ChooseAccountsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/account/ChooseAccountsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/DappLoginUnauthorizedNavGraph.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/accountonetime/OneTimeChooseAccountsNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/accountonetime/OneTimeChooseAccountsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/accountonetime/OneTimeChooseAccountsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/login/DAppUnauthorizedLoginScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/login/DAppUnauthorizedLoginViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/BottomPrimaryButton.kt
profile/src/main/java/rdx/works/profile/di/EncryptionModule.kt

- removed unused `error` property
- created composable out of Dialog used in dapp login flow
- properly update signing state after ledger signature failure
ROLA flow
1. Send accounts request with proof, at least 1 of the accounts should be ledger account
2. Cancel signature or close tab in browser
3. Observe dialog not fully dismissed.

[ABW-2615] Update ledger error handling, remove unused error property and dialog.

---

peerdroid/src/main/java/rdx/works/peerdroid/data/PeerdroidConnector.kt
peerdroid/src/main/java/rdx/works/peerdroid/data/PeerdroidLink.kt
peerdroid/src/main/java/rdx/works/peerdroid/data/webrtc/WebRtcManager.kt
peerdroid/src/main/java/rdx/works/peerdroid/data/webrtc/wrappers/datachannel/DataChannelObserverWrapper.kt
peerdroid/src/main/java/rdx/works/peerdroid/data/webrtc/wrappers/datachannel/DataChannelWrapper.kt
peerdroid/src/main/java/rdx/works/peerdroid/data/websocket/WebSocketClient.kt

This PR fixes termination of WebRTC's job and WebSocket's job when successfully adding a new link connection in wallet settings.
ℹ️   it also incudes a cherry-pick of this [commit of the other PR](https://github.com/radixdlt/babylon-wallet-android/pull/668/commits/9aa046d88f41e9d42583d02e43b481fe6f5a10cb) which contains improved logging for peerdroid module.
⚠️ this will go to the patch release
- Add two or more link connections in your wallet and do some transactions for each of them.
- Then delete one of them and do transactions with the other one.

[ABW-2625] Terminate gracegully WebRTC when adding link connection

---

app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsViewModel.kt
profile/src/main/java/rdx/works/profile/data/model/Profile.kt
profile/src/main/java/rdx/works/profile/data/model/extensions/EntityExtensions.kt

This PR adds Hidden accounts only indication when restoration from backup.
That is the first path:
1. Create at least one account, export the profile, delete the app, go through the restoration and skip seedphrase.
2. After restoration create some new accounts with new main BDFS. 
That is the first path:
3. Hide all previous accounts associated with old BDFS.
4. Export profile and go through restoration.
5. When importing seed phrase accounts from old BDFS, verify that Hidden accounts only box is shown (see screenshot)
Another path:
3. Hide some of the accounts associated with old BDFS, but not all of them.
4. Export profile and go through restoration.
5. When importing seed phrase accounts from old BDFS, verify that you see only accounts that are not hidden, however when you complete …

ABW-2616 - Hidden accounts only box shown when all imported accounts are hidden

---

app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/AccountSecurityScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/LiquidStakeUnitsTab.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/PoolUnitsTab.kt

When selecting a pool unit to transfer with large amounts of redeemable values inside, their titles would be displayed in a new line. The checkbox was taking unnecessary space on the right of the values section, so we moved it on the top right corner, where the name of the pool lays.
**Update**
Also fixed the alignment of the elements when a stake unit's value is too large.
You need to have a pool unit with fungibles with large redeemable values. I hardcoded them in `PoolUnitsTab` just to replicate the issue.
Before
Fix

Fix Pool Units tab checkboxes placement and text alignment

---

webrtc-library/build.gradle

This PR:
- updates the WebRTC library from 116 to 119
- improved the peerdroid logging: removing some unnecessary logs and used more descriptive emojis
- if you don't have a link connection then establish a new one and do some transactions
- if you have a link connection then do some transactions. After that delete the link connection, add a new one, and do some other transactions

[ABW-2612] Update webrtc lib to 119 and imporve peerdroid logging

---

app/build.gradle
app/src/main/res/values-en/strings.xml

This PR changes the way we format new line characters inside strings.xml as they get formatted already by Crowidn.
1. Verify that strings that contained new line characters are displayed correctly for example **recoverSeedPhrase_header_subtitleNoMainSeedPhrase** (see screenshot)

ABW-2597 - Strings containing new lines are modified to contain new line characters.

---

app/src/main/java/com/babylon/wallet/android/presentation/account/createaccount/withledger/CreateAccountWithLedgerScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/importlegacywallet/ImportLegacyWalletScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/ledgerhardwarewallets/LedgerHardwareWalletsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/appsettings/linkedconnectors/AddLinkConnectorViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/appsettings/linkedconnectors/LinkedConnectorsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/appsettings/linkedconnectors/LinkedConnectorsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/AddLinkConnectorScreen.kt
peerdroid/src/main/java/rdx/works/peerdroid/data/PeerdroidConnector.kt
peerdroid/src/main/java/rdx/works/peerdroid/data/webrtc/WebRtcManager.kt
peerdroid/src/main/java/rdx/works/peerdroid/data/webrtc/model/PeerConnectionEvent.kt
peerdroid/src/main/java/rdx/works/peerdroid/data/webrtc/wrappers/datachannel/DataChannelWrapper.kt
peerdroid/src/main/java/rdx/works/peerdroid/data/webrtc/wrappers/peerconnection/PeerConnectionSuspendingWrapper.kt

This PR slightly improves Peerdroid:
- replaced the non concurrent `getValue` with concurrent `get` for `ConcurrentHashMap`s in `PeerdroidConnector`
- `WebRtcManager` will unregister the observer and not close the data channel. `DataChannelWrapper` does this already.
- `DataChannelWrapper` now unregister the observer before closing the data channel
- replace suspending `emit` with `tryEmit` in `createAndObservePeerConnectionForRemoteClient`. No need to suspend the flow there.
- disabled some logs because too many are describing the same thing
You can create a link with this dev tool: https://d13xro4a77czjs.cloudfront.net/ 
and then try the reconnect test and dapp request test. The former repeatedly opens and close the data channel, and the latter sends non stop requests.
We expect the app …

[ABW-2620] Use concurrent methods in PeerdroidConnector and other minor improvements

---

app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsItem.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsNavGraph.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/AccountSecurityNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/AccountSecurityScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/AccountSecurityViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/appsettings/AppSettingsNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/appsettings/AppSettingsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/appsettings/AppSettingsViewModel.kt

This PR moves backups section from **App Settings** into **Account Security & Settings**.
1. Verify that Backup section appears under **Account Security & Settings**.
2. Also make sure that red badge indicating backup state appears on **Account Security & Settings** instead of **App Settings**

ABW-2495 - Backup section moved to Account Security & Settings.

---

app/src/main/java/com/babylon/wallet/android/domain/model/assets/AccountWithAssets.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/account/AccountSelectionCard.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/TargetAccountCard.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/accounts/AccountsChooserDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/accounts/ChooseAccountSheet.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/assets/ChooseAssetsSheet.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/prepare/PrepareManifestDelegate.kt
app/src/test/java/com/babylon/wallet/android/presentation/transfer/TransferViewModelTest.kt
profile/src/main/java/rdx/works/profile/data/model/extensions/AccountExtensions.kt
profile/src/test/java/rdx/works/profile/accountextensions/TransferBetweenOwnedAccountsTest.kt

This PR adds the missing case for the required signature when during an own transfer the receiving account has accept known rule and the spending asset is known by this account. In this case we should not require signature from the user.
In more details:
- enabled rule in isSignatureRequiredBasedOnDepositRules and its unit test
- added logic in the AccountsChooserDelegate to fetch the resources of the target account when "choose" button is clicked
- when "choose" button is clicked, the button is in loading state until the resources are fetched and **the selection of the other accounts remains disabled**
- renamed `assets` to `spendingAssets` in `TargetAccount` state class
1. you have a software `accountS` that contains `resource1`, `resource2`, and a ledger account `accountL` that also …

ABW-2601] Do not require signing when accept known rule and spending asset is in receiving account

---

app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/Dialogs.kt

Bottom sheet dialog no longer dismissed when click on box.
1. Open bottom sheet for fungible/nft or something else and verify that is not being dismiss on click.

ABW-2636 - Bottom sheet is not dismissed upon tap action

---

app/src/main/java/com/babylon/wallet/android/presentation/account/composable/AssetMetadataRow.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/assets/nonfungible/NonFungibleAssetDialog.kt

Data will be displayed in new line when 
1. They are of URL type
2. of String type with more than 40 chars. In the case of strings if they take more than 5 lines to display, we truncate them with a `...Show More` button as previously.
[short-long.webm](https://github.com/radixdlt/babylon-wallet-android/assets/125959264/24c6cf47-596f-44cf-a9f9-ae56f5379842)

Display data in new line when needed

---

app/src/main/java/com/babylon/wallet/android/presentation/status/assets/lsu/LSUAssetDialog.kt

* Removed validator name which was duplicated
* Added validator address below address
* Added description that was missing from LSU.
1. Open an LSU

Add lsu description and validator address

---

app/src/main/java/com/babylon/wallet/android/data/transaction/TransactionClient.kt
app/src/main/java/com/babylon/wallet/android/domain/RadixWalletException.kt
app/src/main/java/com/babylon/wallet/android/presentation/common/UiMessage.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/TransactionAnalysisDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/submit/TransactionSubmitDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletScreen.kt
app/src/main/res/values-en/strings.xml

This PR introduce specific error type when receiving account does not allow deposits.
Please follow iOS PR for more info -> https://github.com/radixdlt/babylon-wallet-ios/pull/908
1. Follow video attached here (including account QR code to scan) -> https://github.com/radixdlt/babylon-wallet-ios/pull/908

ABW-2525 - Introduced specific error type when receiving account does not allow deposits.

---

app/src/main/java/com/babylon/wallet/android/domain/model/assets/AccountWithAssets.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/NFTsTab.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/AccountAssetsRow.kt

This pr fixes the issue for not filtering out correctly validators with stakes that their stake claim is null. Also this PR replaces the number shown in the assets row regarding nfts. It now depicts the number of non-fungible resources the user owns.
Use the profile Umair posted in the ticket. You will see the correct validators shown.

Fix check for filtering out validators with stakes

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Upgrade gradle to 8.2 and get rid of the pop up notification update in Android Studio.
The app has been tested in two different devices after the upgrade. ✅ 
The unit tests run successfully locally. ✅

Upgrade gradle to 8.2

---

app/src/main/java/com/babylon/wallet/android/presentation/account/createaccount/withledger/ChooseLedgerViewModel.kt

PR adds active link connection check when user taps "Continue" when selecting ledger in MARS.
1. Open app go to settings/account recovery and pick ledger option.
2. Add ledger (if not already added).
3. While being on "Choose ledger" screen unlink CE in browser.
4. Select ledger and tap continue.
After this fix wallet detect that there is no CE connection and prompt user to link.

[ABW-2684] Check link connection state before proceeding with account recovery

---

app/src/main/java/com/babylon/wallet/android/presentation/account/AccountScreen.kt

This PR fixes Android 14 padding issue. See ticket to understand the problem.
1. Open account detail screen and verify that bottom nav bar is not coloured same as status bar with gradient.

ABW-2526 - Navigation bar padding added to fix Android 14 issue.

---

app/src/main/java/com/babylon/wallet/android/data/gateway/extensions/StateNonFungibleDetailsResponseItemExtensions.kt

A bug reported on discord by a user who created NFTs with names that are converted to URLs. In the current implementation all NFT data are processed by the wallet, and especially string data are converted to either URL or Address types if they match that type. This conversion should not happen though for NFT data with keys `"name"` or `"description"` as they should be treated as strings, even if they resemble an address or a URL.
Add the address `account_tdx_2_1292jyxrlexx6m877v038jmyjs0cna83l3suppctuy257x5a4unjqds` to your wallet to see a list of NFT collections. One of them is the "Domain Name" collection. Its NFT should now show the domain name.
Previous
Current

Fix nft name when it resembles a url

---

app/src/main/java/com/babylon/wallet/android/data/transaction/TransactionClient.kt
app/src/main/java/com/babylon/wallet/android/domain/RadixWalletException.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/ResolveNotaryAndSignersUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/common/UiMessage.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/TransactionAnalysisDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/submit/TransactionSubmitDelegate.kt
app/src/main/res/values-en/strings.xml
app/src/test/java/com/babylon/wallet/android/data/transaction/TransactionClientTest.kt
app/src/test/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModelTest.kt

This PR forces the transaction review screen to display an error to the user when the entities needed auth, are missing.
All errors that end up to a dialog are terminal errors, meaning that the transaction will close after the user confirms them.
1. Connect some accounts to the sandbox
2. Hide an account
3. Initiate a transaction from sandbox that includes this account
4. You should see the following error. (Added this error to crowdin content may change)

Show error when notary and signers cannot be found

---

app/src/main/java/com/babylon/wallet/android/data/repository/state/StateRepository.kt
app/src/main/java/com/babylon/wallet/android/domain/model/assets/AccountWithAssets.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/StakingTab.kt

When an account has only stake claims, the summary and the validators where showing only the shimmering effect, looking like the stake details were never fetched. This is now fixed.
You need an account with only a claim as an asset an no other stakes. You can achieve that by
1. going to an account that has staking and claims and transfer the claim to another account which has no other staking info.
2. Then you will see the bug (look at the video)
[Bug](https://github.com/radixdlt/babylon-wallet-android/assets/125959264/ed6c8d0b-3755-4540-aa24-64086cb5c54e)
[Fix](https://github.com/radixdlt/babylon-wallet-android/assets/125959264/6a7fd177-8492-4d36-aba9-40e4fc8832a9)

Fix infinite loading in staking tab

---

app/src/main/java/com/babylon/wallet/android/LinkConnectionStatusObserver.kt
app/src/main/java/com/babylon/wallet/android/MainActivity.kt
app/src/main/java/com/babylon/wallet/android/data/dapp/LedgerMessenger.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/createaccount/withledger/ChooseLedgerScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/createaccount/withledger/ChooseLedgerViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsItem.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/importlegacywallet/ImportLegacyWalletScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/importlegacywallet/ImportLegacyWalletViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/ledgerhardwarewallets/AddLedgerDeviceViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/ledgerhardwarewallets/LedgerHardwareWalletsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/ledgerhardwarewallets/LedgerHardwareWalletsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/appsettings/AppSettingsNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/debug/DebugSettingsNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/debug/DebugSettingsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/debug/DebugSettingsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/AddLedgerDeviceScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/DevelopmentPreviewWrapper.kt
app/src/test/java/com/babylon/wallet/android/presentation/createaccount/withledger/AddLedgerDeviceViewModelTest.kt
app/src/test/java/com/babylon/wallet/android/presentation/createaccount/withledger/ChooseLedgerViewModelTest.kt
core/src/main/java/rdx/works/core/preferences/PreferencesManager.kt
peerdroid/src/main/java/rdx/works/peerdroid/data/PeerdroidConnector.kt
peerdroid/src/main/java/rdx/works/peerdroid/domain/PeerConnectionStatus.kt

This PR 
- fixes when showing the add new link connector screen. Specifically, wallet shows that screen only when no link connectors configured in settings. We do not check if the linked connectors are connected any more.
- added a loading spinner in the "add ledger device" button while user is linking a new connector
Added a peer connection status indicator (not data channel status!) which is shown as a dot at the top of the system's bar.
- indicator turns **red** as long as the peer connection is in **disconnected** state
- indicator turns **yellow** as long as the peer connection is in **connecting** state
- indicator turns **green** as long as the peer connection is in **connected** state
1. Add a new link connector
2. Forget link connection from the CE of the browser, but do not …

[ABW-2754] Show add link connector screen only when no link connectors available and connector status indicator

---

webrtc-library/build.gradle

This PR updates the WebRTC lib from M119 to M121
1. Add a new link connector
2. Execute a few transactions between wallet and dapp
3. Test it also by having your laptop and device connected to separate networks (different WiFi, or different bands one one 2.4 the other on 5, mobile data, ....)

[ABW-2857] Update WebRTC lib to M121

---

app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/CommonTransferContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/ConnectedDAppsContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/PoolsContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/ValidatorsContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/ValidatorDetailsItem.kt

Transaction review look aligned with Zeplin regarding Pools/ Stakes and ConnectedDApps container.
-  Trigger transfer showing Pools and compare with Zeplin.
Before: 
After:

ABW-2842 - Screen aligned with the Zeplin design.

---

app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionPreviewHeader.kt

This solution is a hack but didn't want to spend more time on this. 
It fixes the problem of scroll flickering which sometimes makes impossible to reach Sign Transaction slide button.
Im sure there must be more elegant solution but didn't find it in this time frame.
To describe when exactly the problem exists:
For Transaction Review screens that hold longer content was fine.
The problem occurred for content short enough to perform motion layout animation.
So depending on initial ScrollState.maxValue I set larger or shorter animation threshold (called animationRange in the code)
Please trigger some transaction as shown in below videos.
Before:
https://github.com/radixdlt/babylon-wallet-android/assets/108684750/a6720657-6627-4dd8-86bd-855447ef9d19 …

ABW-2732 - Increase animation threshold which changes the progress for shorter contents.

---

app/src/main/java/com/babylon/wallet/android/data/gateway/extensions/StateNonFungibleDetailsResponseItemExtensions.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/composable/AssetMetadataRow.kt

IN this PR we convert the epoch date of an instant NFT data entry to a human readable date.
You either need a NFT with instant data attached to it. If you don't own one you can attach this code temporarily for testing in `NFTEntity L24`:
```
metadata = metadata?.metadata.orEmpty().toMutableList().apply {
add(
Metadata.Primitive(
key = "maturity_date",
value = "1705965360",
valueType = com.babylon.wallet.android.domain.model.resources.metadata.MetadataType.Instant
)
)
}
```
This will result in every NFT saved in your wallet to have an entry like this 👇

Show Instant as date in NFT data

---

app/src/main/java/com/babylon/wallet/android/presentation/navigation/NavigationHost.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/dapp/DAppDetailsDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/dapp/DAppDetailsDialogNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/card/FungibleCard.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/card/NonFungibleCard.kt

DAppDetailsDialog is now able to click on the associated fungibles and non fungibles. Also the text changed to associated NFTs for the non fungibles section. 
1. Better use gumball club to do a transaction.
2. Click on the Using dapps section 
3. Then click on a fungible or non fungible associated with gumball club
[dappdetails.webm](https://github.com/radixdlt/babylon-wallet-android/assets/125959264/1ad7b79b-8d80-402b-a4ba-dc3dd6eba71a)

Allow click on fungibles & NFTs from dApp details sheets

---

app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionPreviewHeader.kt

This PR changes the tile of the Tx review to be always Review Your Transaction.

ABW-2820 - Review your transaction title changed.

---

app/src/main/java/com/babylon/wallet/android/utils/Constants.kt

Just a minor change to the URL 
from: `https://wallet.radixdlt.com/`
to: `https://wallet.radixdlt.com/?wallet=downloaded`

Add downloaded parameter to radix banner link

---

app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionAccountCard.kt

This PR fixes duplicated page open on multiple click on tx review screen.
1. Trigger Stake / Unstake transaction or even the transfer (fungible/nonfungible click was affected too)
2. Verify that upon multiple click, only one detail page is open.
https://github.com/radixdlt/babylon-wallet-android/assets/108684750/1a6c3a05-2da6-48c3-8053-834c2bc4f27c

ABW-2848 - Asset detail page open only once in case of duplicate press on the transaction review.

---

app/src/main/java/com/babylon/wallet/android/domain/RadixWalletException.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/submit/TransactionSubmitDelegate.kt

Ledger transaction with blind signing disabled end up with proper error dialog. 
1. Make sure that blind singing is disabled on your ledger app.
2. Trigger some ledger transaction (for example create token from ledger account)
3. Verify that error is shown when signing fails due to blind singing disabled (see video)
https://github.com/radixdlt/babylon-wallet-android/assets/108684750/8546dd30-fe23-49fb-b433-d9691cdc09b5

ABW-2734 - Blind singing error dialog shown.

---

app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/Thumbnail.kt

This PR fixes GIF/SVG and WEB (incl animated) image support.
1. Ideally create NFT with such an image, but you can go directly to Thumbnail.kt L155 to replace the image with any you prefer. Here are some examples:
https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotating_earth_%28large%29.gif
https://upload.wikimedia.org/wikipedia/commons/d/d7/Android_robot.svg
https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/410.svg
https://www.gstatic.com/webp/gallery/1.webp
https://res.cloudinary.com/demo/image/upload/fl_awebp/bored_animation.webp
Note that animated WebP are not currently working because of image service not supporting them. You can verify it by supporting url without image service and see if its works.
https://github.com/radixdlt/babylon-wallet-android/assets/108684750/658a881f …

ABW-2867 - GIF/SVG/WEBP support added.

---

app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/PoolContributionProcessor.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/ValidatorClaimProcessor.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/ValidatorStakeProcessor.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/ValidatorUnstakeProcessor.kt
app/src/test/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModelTest.kt

- compute guarantees for stake/pool tx types
- in pool contribution, resolve asset using general rules if there is no pool associated (example to test this case, set up pool that has 10:1 ratio of Asset A to Asset B, and contribute 110 asset A and and 10 Asset B - in preview you will see pool unit deposited and 10 units of Asset A)
- optimize stake claim processor - we don't need `TrackedClaim` object to produce model representing tx preview in that case

Compute stake/pool preview guarantees state

---

app/src/main/java/com/babylon/wallet/android/presentation/model/ActionableAddress.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/assets/fungible/FungibleDialogContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/assets/nonfungible/NonFungibleAssetDialogContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/ActionableAddressView.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/resources/AddressRow.kt

1. Links to pool addresses resolve to the correct page
2. Resource addresses and local ids for newly created entities do not show the `View in Radix Dashboard` action.
1. Do a pool contribution or redemption. Click on the pools sheet and visit the dashboard for a pool address
3. Create a token or an NFT and long click on the resource address or also the local id for the NFT. All should not show the View in Radix Dashboard action.

Dashboard link bugs

---

app/src/main/java/com/babylon/wallet/android/presentation/account/settings/thirdpartydeposits/AccountThirdPartyDepositsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/AccountDepositSettingsTypeContent.kt

Changed icon for accept known rule.
Added icon container in transaction review page when settings deposit rule.
1. Go to accounts third party deposit
2. Change deposit rule
3. Verify that correct icons are displayed.

ABW-2899 - Icon added to deposit rules content in transaction review. Icon for accept known fixed.

---

app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/Thumbnail.kt

Pool unit icon from a rounded rect is now a circle.
1. Open a pool unit in an account or in a transaction

Make Pool unit Thumbnail a circle

---

app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/CommonTransferContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/PoolsContent.kt

When expanding pools, bottom part does not cut off upon animation.
1. Trigger pool contribution
2. Expand and collapse Pools section
3. Observed that view is not cut off upon animation.
https://github.com/radixdlt/babylon-wallet-android/assets/108684750/ce6b93c3-8731-471a-996c-244eb097b9c5

ABW-2860 - Bottom padding changed to get rid of padding being involved in animation.

---

app/src/main/java/com/babylon/wallet/android/data/repository/cache/database/StateDao.kt
app/src/main/java/com/babylon/wallet/android/domain/model/assets/PoolUnit.kt
app/src/main/java/com/babylon/wallet/android/presentation/navigation/NavigationHost.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/assets/AssetDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/assets/AssetDialogNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/assets/AssetDialogViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/assets/fungible/FungibleDialogContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/assets/lsu/LSUDialogContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/assets/pool/PoolUnitDialogContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/PoolContributionProcessor.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/CommonTransferContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/DepositAccountContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/PoolTypeContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/StakeTypeContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionAccountCard.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransferTypeContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/WithdrawAccountContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/PoolUnitsTab.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/resources/TokenBalance.kt

As discussed in standup, when there is the first time the user contributes to a pool or stakes to a validator with no stakes at the moment, the asset details screen would not show the correct amounts. Since Asset details was built to show whatever ledger knows at this point in time. Actions in transaction review are not yet submitted on ledger and might cause discrepancies on what the user sees in TR screen and what sees in Asset details screen.
The way to handle it is to pass the amounts involved as a map:
```
Map<Resource Address, BigDecimal>
```
This applies for fungibles. 
1. For tokens the amount of the token is passed in this map 
```
mapOf(token.address to token.amount)
```
2. For LSUs the amount of the LSU and the 
```
mapOf(
lsu.address to lsu.amount,
XRD.address to lsu.xrdWorth …
```

Asset details with correct amounts in transaction review

---

app/src/main/java/com/babylon/wallet/android/presentation/settings/recovery/chooseseed/ChooseSeedPhraseScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/recovery/chooseseed/ChooseSeedPhraseViewModel.kt

Continue button disabled if no seed phrase has been selected.
1. Go to Account Recovery Scan
2. Make sure you have two seed phrases available
3. When entering Choose Seed Phrase screen verify that Continue button is disabled (greyed out) if no seed phrase is selected.
https://github.com/radixdlt/babylon-wallet-android/assets/108684750/c063906d-db5d-4ff3-b12a-45bd4dfd7b3c

ABW-2853 - Continue button greyed out if no seed phrase selected in Account Recovery Scan.

---

app/src/main/java/com/babylon/wallet/android/presentation/account/settings/specificassets/SpecificAssetsDepositsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/settings/specificdepositor/SpecificDepositorScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/assets/nonfungible/NonFungibleAssetDialogContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/AccountDepositSettingsTypeContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionAccountCard.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/assets/SpendingAssetItem.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/Thumbnail.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/NFTsTab.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/StakingTab.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/card/NonFungibleCard.kt

Make all nf thumbnails to be rounded rectangles

---

app/src/main/java/com/babylon/wallet/android/presentation/account/createaccount/withledger/ChooseLedgerScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/createaccount/withledger/ChooseLedgerViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/importlegacywallet/ImportLegacyWalletScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/ledgerhardwarewallets/AddLedgerDeviceViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/ledgerhardwarewallets/LedgerHardwareWalletsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/AddLedgerDeviceScreen.kt

This PR  fixes several bugs in the choose and add ledger screens.
- if at least one linked connector is configured in the wallet then every screen that involves a ledger will try to send messages over the data channel **no matter if it is open or closed**. In case it's closed we show the appropriate ui message "failed to connect..."
- if no linked connectors are configured in the wallet then every screen that involves a ledger will show the "add link connector screen" when wallet tries to send a message over the data channel
**Use case 1**
1. add a link connector in the wallet
2. create an account with an existing ledger 
3. create another account by adding a new ledger (during the account creation flow)
verify that everything works as expected
---
**Use case 2**
1. add a link connector …

[ABW-2898] Simplify choose and add ledger screens

---

app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransferablePoolUnitItemContent.kt

When the pool unit amount transferred is guaranteed we should show it.
1. Do a transfer of a pool unit amount. You should see the amount just like for tokens
2. Do a contribution. You should see an estimated/guaranteed section instead of just the amount.

Show guaranteed amount for pool units if exists

---

app/src/main/java/com/babylon/wallet/android/domain/usecases/GetEntitiesWithSecurityPromptUseCase.kt

- right now we react to any change in backed up factor sources. When we finish factor source seed restoration, we mark this factor source as backed up. But list already contained that factor source, since we don't remove it's id from the list when mnemonic access is lost due to encryption key change (on device security change).
1. Remove device screen lock.
2. Re-add the lock
3. Open Wallet, restore main seed phrase.
4. Verify that recover prompt is gone from account cards

[ABW-2920] Refresh security prompt after seed phrase was restored

---

app/src/main/AndroidManifest.xml

- exclude permissions that appear to be added automatically to merged manifest
How I tested it is I run app with crashlytics enabled on lowest supported android api level - 27 and on android 14, and appear that crash reports are being sent. Still I'm unsure if those permissions will be removed from final build, as I don't see Crashlytics manifest to declare `targetSdk`, which is supposedly trigger for adding the additional permissions.

[ABW-2932] Exclude questionable permissions

---

app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/AccessFactorSourcesDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/recover/scan/AccountRecoveryScanScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/settings/devsettings/DevSettingsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/account/ChooseAccountsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/personaonetime/PersonaDataOnetimeScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/personaongoing/PersonaDataOngoingScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/selectpersona/SelectPersonaScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/accountonetime/OneTimeChooseAccountsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/personaonetime/PersonaDataOnetimeScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonic/AddSingleMnemonicScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/importlegacywallet/ImportLegacyWalletScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/seedphrases/SeedPhrasesScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/seedphrases/confirm/ConfirmMnemonicScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/PersonasScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/createpersona/CreatePersonaScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/personadetail/PersonaDetailScreen.kt
app/src/main/java/com/babylon/wallet/android/utils/BiometricExtensions.kt
app/src/main/java/com/babylon/wallet/android/utils/ContextExtensions.kt

This PR refactors the biometric extension function to return result instead of boolean. 
Currently we return `false`  for both failed auth and other error (e.g. user dismisses biometric auth). Now, we need to distinguish those two cases.

Refactor biometric extension to return result

---

app/src/main/java/com/babylon/wallet/android/presentation/account/AccountScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/composable/FiltersDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/composable/FiltersStrip.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/composable/HistoryFilterTag.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/history/HistoryScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/history/HistoryViewModel.kt
app/src/main/java/com/babylon/wallet/android/utils/DateExtensions.kt
core/src/main/java/rdx/works/core/BigDecimalExtensions.kt
core/src/test/java/com/babylon/wallet/core/DisplayableQuantityTest.kt

Following issues are fixed:
- https://radixdlt.atlassian.net/browse/ABW-2988 - issue here is bug in value formatting code, we need to use `toPlainString` before we start to process the value, otherwise we can get scientific notation string which is not expected input to `displayableQuantity`. See additional test I've added for that case
- https://radixdlt.atlassian.net/browse/ABW-3000 by mistake selected filters strip shared same scroll state as month selector
- https://radixdlt.atlassian.net/browse/ABW-2996 add "Today", "Yesterday" prefix to history date headers, if applicable
- remove X to close for history filter tags in a FilterDialog. Tags in history view (above month strip) still have X 
1. first bug is only possible to test if you have near zero amount in the wallet, or using …

Minor history bugs

---

app/src/main/java/com/babylon/wallet/android/data/repository/tokenprice/FiatPriceRepository.kt
app/src/main/java/com/babylon/wallet/android/di/DataModule.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/assets/GetFiatValueUseCase.kt
app/src/test/java/com/babylon/wallet/android/domain/usecases/GetFiatValueUseCaseTest.kt

The PR adds to the repository introducing a Testnet implementation which
1. for testnet xrd addresses, requests mainnet's xrd price
2. for the rest of addresses, returns a random result from real tokens that exist on mainnet
3. if the build is not in debug mode (`EXPERIMENTAL_FEATURES_ENABLED`) then `PricesNotSupportedInNetwork` is returned so the UI can act accordingly.
The testnet repository will relay to the mainnet repositoryby requesting mainnet addresses. So no need for re-implementing the caching logic.

Show virtual values in non Mainnet network for debug builds

---

app/src/main/java/com/babylon/wallet/android/presentation/account/history/HistoryViewModel.kt

Now we don't preselect first month on the list until history load
1. Open account history which does not have tx in current month, but has some in the past

[ABW-3050] Set selected month whne history first loads

---

app/build.gradle
app/src/main/java/com/babylon/wallet/android/data/repository/stream/StreamRepository.kt
app/src/main/java/com/babylon/wallet/android/domain/RadixWalletException.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/assets/UpdateAccountFirstTransactionDateUseCase.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/transaction/PollTransactionStatusUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/history/HistoryViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionPreviewHeader.kt
app/src/main/res/values-en/strings.xml
core/build.gradle
core/src/main/java/rdx/works/core/preferences/PreferencesManager.kt
profile/src/main/java/rdx/works/profile/data/model/apppreferences/Transaction.kt

- assertion failure message
- lower defaut deposit guarantee value - 0.99
- enable crashlytics in firebase alpha build
- make title in tx review screen fixed size not dependent on system font scale setting to avoid excessive whitespace
1. Execute tx with guarantees > 100%
2. Observe failure message
I took screenshot before adding % symbol to a string

Assertion failed message and lower default deposit guarantee

---

app/src/main/java/com/babylon/wallet/android/presentation/account/history/HistoryScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/history/HistoryViewModel.kt

- Adds sticky headers for date type items in history list. 
- simplify list state monitoring - current implementation does not use fixed items at the top, so we don't need additional scroll logic.
1. Play with history and verify if it works as expected, data is still loaded and jumping between months sets proper position on the list/month strip

[ABW-3049] History dates sticky headers

---

app/src/main/java/com/babylon/wallet/android/presentation/status/assets/AssetDialogViewModel.kt

Only show fiat values in account context.
1. Open asset details from tx review and verify there is no infinite shimmer

[ABW-3070] Show fiat values in account context only

---

app/src/main/java/com/babylon/wallet/android/presentation/account/composable/AssetMetadataRow.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/signing/FactorSourceInteractionBottomDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/transaction/TransactionStatusDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/Dialogs.kt

- add additional parameter that control if we show or not default dialog wrapper top bar
- center metadata view content and add spacing between label/value
1. Open Various NFT details and verify dialog is now displayed properly, with drag to dismiss working

[ABW-3069] Fix NFT asset details dialog

---

app/src/main/java/com/babylon/wallet/android/domain/model/assets/AssetPrice.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/TotalFiatBalanceView.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt

This PR fixes:
- the text color of the balance when is 0
- the format of the balance when is 0. Now it should be "0" instead of "0.00"
- the loading of total wallet fiat balance
1. You need a wallet with empty accounts

[ABW-3061] Fix format when balance is zero

---

app/src/main/java/com/babylon/wallet/android/data/repository/cache/database/TokenPriceDao.kt
app/src/main/java/com/babylon/wallet/android/data/repository/tokenprice/FiatPriceRepository.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/assets/GetFiatValueUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/AccountViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/assets/AssetDialogViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/assets/AssetsChooserDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt
app/src/test/java/com/babylon/wallet/android/domain/usecases/GetFiatValueUseCaseTest.kt
app/src/test/java/com/babylon/wallet/android/fakes/FiatPriceRepositoryFake.kt

This PR adds functionality 
- to update the prices when the user pulls to refresh in Wallet screen and Account screen
- to always request the last updated prices in Choose Assets screen of the Transfer screen and in the Asset dialog

Update prices when pull to refresh

---

app/build.gradle
app/proguard-rules.pro
app/src/main/java/com/babylon/wallet/android/NPSSurveyStateObserver.kt
app/src/main/java/com/babylon/wallet/android/data/repository/TransactionStatusClient.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/transaction/PollTransactionStatusUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/history/HistoryViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/transaction/TransactionStatusDialogViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/survey/NPSSurveyDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt
app/src/test/java/com/babylon/wallet/android/domain/usecases/NPSSurveyStateObserverTest.kt
app/src/test/java/com/babylon/wallet/android/fakes/FakePreferenceManager.kt
app/src/test/java/com/babylon/wallet/android/presentation/WalletViewModelTest.kt
core/src/main/java/rdx/works/core/preferences/PreferencesManager.kt

- properly trigger blank nps request when tapping X or swiping to close the NPS survey
- prevent listening to poll status twice. Because in the past we incremented tx counter in the status dialog collect P {} block, every transaction resulted in increment of 2.
- moved increment code to the transaction poll client, where it is run in app scope so we can be certain it is run even if status dialog go away
- make sure we can't fire NPS dialog twice even if status flow would emit multiple times. Dialog can only be shown again after current one is dmissed
- added change to history date selection logic - now when we have everything loaded and we tap on a month that does not have a transaction, we scroll to first tx before that date. Added comments on the logic as well
1. Dismiss the dialog by …

NPS survey fixes

---

app/src/main/java/com/babylon/wallet/android/presentation/status/transaction/TransactionStatusDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/Dialogs.kt

- update dialog styling
- updated error copy
- added X icon and drag handle to tx status dialogs
1. Run tx and verify success/failure state. To trigger assertion error, customisze guarantees of a tx to be over 100% (for example pool contribution)

[ABW-3086] update tx failure dialog styling

---

app/src/main/java/com/babylon/wallet/android/domain/model/assets/AssetPrice.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/TotalFiatBalanceView.kt

This PR fixes the balance representation by relying only on native formatter.
previews to the rescue!
actual values are: `0`, `246.608903`, `0.608903`, `0.0000000003` in this order

Fiat balance representation based on native formatter

---

app/src/main/java/com/babylon/wallet/android/data/repository/tokenprice/FiatPriceRepository.kt

This PR fixes an issue with the testnet when the token price service returns an empty map of prices.

Fix random fiat value when empty list of prices

---

app/src/main/java/com/babylon/wallet/android/data/repository/stream/StreamRepository.kt
app/src/main/java/com/babylon/wallet/android/domain/RadixWalletException.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/composable/TransactionHistoryItem.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/accountsecurity/depositguarantees/DepositGuaranteesScreen.kt
app/src/main/java/com/babylon/wallet/android/utils/StringExtensions.kt

- remove additional data that we don't use for transaction history call
- remove default "Pool Units" text from transaction history

Remove unused opt-ins and placeholder text for pool units

---

.github/workflows/pr_and_main.yml
.github/workflows/publish_releases.yml

`--json-file-output` parameter stopped working properly but the same effect can be achieved with stdout redirect `>`

ci: restore snyk sbom

---

app/src/main/java/com/babylon/wallet/android/presentation/account/AccountScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/AccountViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/assets/AssetDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/assets/AssetDialogViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/assets/AssetsChooserDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/assets/ChooseAssetsSheet.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/AccountCardView.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt

This PR hides the fiat balances when the wallet is not on mainnet
1. in the `TestnetFiatPriceRepository` class change the lines 160 and 171 to true: `if (BuildConfig.EXPERIMENTAL_FEATURES_ENABLED)`
2. run the wallet switch to stokenet -> wallet should not show any prices in wallet, account, transfer screens and asset dialogs

Fix hide balances when not on mainnet

---

app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt

This PR fixes visibility of fiat prices when switching networks.
This fix is not required in other screens since the other screens get the initial state with `isFiatBalancesEnabled` to true (default value).
1. in the TestnetFiatPriceRepository class change the lines 160 and 171 to true: if (BuildConfig.EXPERIMENTAL_FEATURES_ENABLED)
2. run the wallet switch to stokenet -> wallet should not show any prices in wallet, account, transfer screens and asset dialogs
3. switch back to mainnet -> fiat prices should be visible

Enable fiat prices when no PricesNotSupportedInNetwork exception

---

app/src/main/java/com/babylon/wallet/android/presentation/account/AccountScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/TotalFiatBalanceView.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/AccountCardView.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletScreen.kt

This PR adds logic to toggle visibility of fiat balance when user click on total fiat balance view on Account and Wallet screens.
1. Click on total fiat balance in Account and Wallet screens
https://github.com/radixdlt/babylon-wallet-android/assets/118305718/7dee70d5-4bdc-4a41-a954-54d926588ea1

[ABW-3107] Toggle visibility when click on balance

---

app/src/main/java/com/babylon/wallet/android/presentation/account/settings/AccountSettingsScreen.kt

This PR updates copy for 'Hide Account' button in Account Settings screen. Also, added 'Hide This Account' title to the confirmation alert.

Update 'Hide account' button copy in account settings

---

app/src/main/java/com/babylon/wallet/android/domain/RadixWalletException.kt

The error message misleading since the parameters were reverted. The request network name should be first and the current network name should be second. Since the string is `dApp made a request intended for network %s, but you are currently connected to %s.`
1. Change wallet to stokenet
2. Try to login from any dapp in mainnet
3. You should see the correct error message

Fix request/current network name in error message

---

app/src/main/java/com/babylon/wallet/android/presentation/account/settings/AccountSettingsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/settings/AccountSettingsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/settings/devsettings/DevSettingsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/settings/devsettings/DevSettingsViewModel.kt
app/src/test/java/com/babylon/wallet/android/presentation/accountsettings/AccountSettingsViewModelTest.kt
app/src/test/java/com/babylon/wallet/android/presentation/accountsettings/DevSettingsViewModelTest.kt

[Jira Ticket](https://radixdlt.atlassian.net/browse/ABW-3133)
Hidden dev settings section for non-debug builds. 
Moved XRD test tokens to Account settings screen
Account Settings screen on a non-debug build:
Video showcasing XRD test tokens button being moved from Dev Preferences to Account Settings screen and being shown only for stokenet gateway.
https://github.com/radixdlt/babylon-wallet-android/assets/164897324/dcfaa156-7fa6-4de3-9857-c346c7d91d20

[ABW-3133] Account settings XRD faucet placement

---

app/src/main/java/com/babylon/wallet/android/presentation/account/history/HistoryViewModel.kt

- update history state with genesis tx instant. After that it is used in history calls. Probably removed that during the rebases

update history state with genesis tx instant

---

app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/derivepublickey/DerivePublicKeyViewModel.kt

When creating first account (ledger or device) we need to authenticate since BDFS will be created. This was probably missed during FS refactor.
1. Fresh wallet install, create account with ledger.
2. Before the change app will crash when selecting ledger

Authenticate first when creating first ledger account (and BDFS)

---

app/src/main/java/com/babylon/wallet/android/data/transaction/InteractionState.kt
app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/deriveaccounts/DeriveAccountsDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/derivepublickey/DerivePublicKeyDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/signing/FactorSourceInteractionBottomDialog.kt

This PR:
- updates the strings for the new keys that have been added in localization
- removed some unused code

Update access factor sources strings

---

app/build.gradle
profile/src/main/java/rdx/works/profile/data/model/extensions/CreateAccountExtensions.kt
profile/src/main/java/rdx/works/profile/data/model/extensions/FactorInstanceExtensions.kt
profile/src/main/java/rdx/works/profile/data/model/pernetwork/FactorInstance.kt
profile/src/main/java/rdx/works/profile/data/model/pernetwork/FactorInstanceSerializers.kt
profile/src/test/java/rdx/works/profile/Secp256k1PublicKeyWithWrongCurveTest.kt
profile/src/test/resources/raw/secp256k1_public_key_with_curve25519_error.json

Here is the issue https://radixdlt.atlassian.net/browse/ABW-3233
- setup wallet
- do account recovery scan for olympia seed phrase that will result with at least 1 account added to profile
- on next wallet run you will see bdfs, and when you will try to execute transaction with this account as signer (for example transfer from that account), preview will return error
Executing above after the fix should not fire bdfs error and transactions with this account should be possible now

[ABW-3233] Properly set curve of account public key for legacy olympia accounts

---

app/src/main/java/com/babylon/wallet/android/presentation/account/history/HistoryViewModel.kt

- in case there is no transaction (and no initial timestamp) we don't compute time filters and don't set timestamp in filters
1. Open history of an empty account - you should see empty state

[ABW-3245] Fix empty history crash

---

app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/SecurityCenterScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/backup/BackupScreen.kt

https://radixdlt.atlassian.net/browse/ABW-3305
https://radixdlt.atlassian.net/browse/ABW-3298
https://radixdlt.atlassian.net/browse/ABW-3300
https://radixdlt.atlassian.net/browse/ABW-3296
- updated configuration backup screen
- changed wrong security settings copies
- updated styling of encryption password sheet
Please note that logic for displaying backup state, last synced time etc is not implemented until new backup system is done.
1. Check that backup screen

Settings ui fixes

---

app/src/main/java/com/babylon/wallet/android/presentation/common/seedphrase/SeedPhraseInputDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonic/AddSingleMnemonicScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/importlegacywallet/ImportLegacyWalletScreen.kt

1. Verify that warning is not shown on seed phrase entry screen if all inputs are empty

[ABW-3285] Display incorrect seed phrase warning only if input is non empty

---

app/src/main/java/com/babylon/wallet/android/presentation/common/seedphrase/SeedPhraseInputDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonic/AddSingleMnemonicScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/importlegacywallet/ImportLegacyWalletScreen.kt

- with previous Seed phrase validation fix https://github.com/radixdlt/babylon-wallet-android/pull/909 I actually missed that same flag was controlling both warning visibility & "Continue" button enabled state. Additionally those flags are used in 3 places, which needed update as well.

[ABW-3285] Split state of seed phrase warning & and it's validity

---

app/src/main/java/com/babylon/wallet/android/domain/usecases/SearchFeePayersUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/FeePayerSelectionContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/FeesSheet.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/GuaranteesSheet.kt
app/src/test/java/com/babylon/wallet/android/domain/usecases/SearchFeePayersUseCaseTest.kt

* Fee payers include the amount of XRD on each account
* Transaction fee message changed
* Accounts with 0 XRD are filtered out from fee payers list as iOS does.
1. Create 3 accounts
2. Put all xrd in one account
3. Transfer 0,1 XRD to the second account
4. Leave the third account empty
5. Do a transfer of any XRD from 1st to any account. 
6. Then in the list you should see fee payers as:
* 1st Account
* 2nd Account (which has insufficient funds, since the fee will logically be larger than 0,1)
* The 3rd account should not be visible
* If you select the 2nd Account, the message of insufficient funds will be displayed.
7. For some reason the selected fee payer was not pre-selected and the selection state was not kept. This PR also fixes this problem

Transaction fees fixes

---

app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsItem.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/SecurityCenterScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/backup/BackupScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/backup/BackupViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/TroubleshootingSettingsNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/TroubleshootingSettingsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/TroubleshootingSettingsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/reset/FactoryResetNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/reset/FactoryResetScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/reset/FactoryResetViewModel.kt
designsystem/src/main/res/drawable/ic_factory_reset.xml

- factory reset replaces "Delete" currently located in backup screen
- security center state should be double checked after new backup implementation is in place
1. Verify that Delete is no longer available in Bacup Screen and Factory Reset option is present

[ABW-3310] Factory reset option in troubleshooting settings

---

app/src/main/java/com/babylon/wallet/android/domain/usecases/GetEntitiesWithSecurityPromptUseCase.kt

Before the fix, I was displaying "Recovery Required" and "Accounts and personas not recoverable" problems at the same time. My misunderstanding of intended behavior here.
1. Restore profile that has some entites from backup but skip entering mnemonics.
2. After the fix you will only see "Recovery required" for a given seed phrase.

[ABW-3321] Display one security prompt per account at a time

---

core/src/main/java/rdx/works/core/EncryptionHelper.kt

- apparently on some devices using strongbox produces subtype of `ProviderException`, and not `StrongBoxUnavailableException` specifically. Only change here is that we catch exception properly.

[ABW-3320] Key generation issue on some devices

---

app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt

This PR fixes accounts refresh [issue](https://radixdlt.atlassian.net/browse/ABW-3227) after network switching.
Each time the user requests a refresh or the accounts change (for example when switching the network), we start fetching the fiat prices for every account asynchronously. Switching multiple times between the networks results in as many fetching operations launching which delays the accounts loading and displaying more and more. The fix is to stop waiting for the result of the previous fetching operation when a new one has started.
1. Import a backup with many accounts (I've tested with 39 accounts on main and 27 on stokenet and the issue is very easy reproducible)
2. Refresh the account list
3. Switch network gateway from Settings -> Preferences
4. Go back to the account list …

Fix account refresh issue after network switching

---

app/src/main/java/com/babylon/wallet/android/presentation/account/settings/specificassets/SpecificAssetsDepositsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/settings/specificdepositor/SpecificDepositorScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/preferences/gateways/GatewaysScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/Dialogs.kt

Modal bottom sheet from material3 library somehow prevent TextField contexttual actions to show, see [this](https://issuetracker.google.com/issues/327085717). Replaced it with our own bottom sheet dialog, as we done on transfer screen while ago. 
1. Check that add gateway, add specific depositor, add asset rule dialogs work as before.
2.

[ABW-3199] Replace ModalBottomSheet to allow text field context actions to show

---

app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/AddLedgerDeviceScreen.kt

So far this crash manifest itself only on samsung devices.
- don't update state of text field after we started process of storing ledger device and closing the screen
- close keyboard when user confirms saving ledger device.
I could easily reproduce issue on galaxy s21 ultra, and after the fix problem was gone.
1. Try to add ledger device in account creation (first time) or from Security Factors/Ledger Devices. Make sure keyboard is visible on screen when tapping "Continue"

[ABW-3312] Fix compose IME crash when adding a ledger

---

app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt

This PR fixes accounts loading in the wallet screen.
The recent changes to the code made the `accountsFlow`in `WalletViewModel` not emitting anything upon creation. I think it was emitting before due to more code being executed at the viewModel creation thus delaying the emit to `refreshFlow` in `loadAssets`method. The fix is for the `refreshFlow` to take an initial value upon collection.

Fix accounts loading in wallet screen

---

app/src/main/java/com/babylon/wallet/android/data/repository/tokenprice/FiatPriceRepository.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/AccountViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt

[Ticket](https://radixdlt.atlassian.net/browse/ABW-3338)
This PR updates the displayed value for assets' worth from "0" to "-" when the token prices API fails and there are no prices saved in db. 
[untitled.webm](https://github.com/radixdlt/babylon-wallet-android/assets/164897324/684fa0bb-9ff9-44d7-a20b-092059a382d1)

Show dash instead of zero when token prices are not available

---

app/src/main/java/com/babylon/wallet/android/data/repository/p2plink/P2PLinksRepository.kt
app/src/main/java/com/babylon/wallet/android/presentation/main/MainViewModel.kt
profile/src/main/java/rdx/works/profile/domain/GetProfileUseCase.kt

This PR fixes connecting to a ledger device when creating the first account during onboarding.
The issue was that the p2p links connection was conditioned by the profile being initialized, but we need p2p links connection during onboarding when adding a ledger device and there is no restored profile.
Case 1:
1. Choose "I'm a new radix wallet user"
2. Skip until "Create First Account" screen
4. Check "Create with ledger hardware wallet"
5. Click "Add Ledger Device"
6. Link a connector
7. Click "Continue" and make sure the ledger connection request is displayed in the browser
Case 2:
1. Create/restore a profile
2. Add a linked connector from settings
3. Factory reset wallet
4. Create/restore a profile
5. Make sure the accounts are synced with the connector extension and/or the dApp requests …

Fix connecting to ledger device when creating first account

---

profile/src/main/java/rdx/works/profile/cloudbackup/domain/CheckMigrationToNewBackupSystemUseCase.kt
profile/src/main/java/rdx/works/profile/domain/backup/RestoreProfileFromBackupUseCase.kt

There is this edge case were an old user had backed up with the previous backup system, deleted the app and installed the new one.
In the restoration process, logs in and selects the backup (restored from the old backup system `DeprecatedCloud`) and proceeds to restore the seed phrase. The migration screen was still shown.
So to fix that we also need to check that either a backup with the new system has not occurred by looking at the preference that shows that the previous system is in use and the user is not signed in yet.
Also in order to avoid showing the migration modal, we also remove the preference used by the old system, when the user restored from deprecated cloud.

Refine when the migration to new backup system screen is shown

---

app/src/main/java/com/babylon/wallet/android/presentation/walletclaimed/ClaimedByAnotherDeviceViewModel.kt
profile/src/main/java/rdx/works/profile/cloudbackup/data/DriveClient.kt
profile/src/main/java/rdx/works/profile/domain/backup/RestoreProfileFromBackupUseCase.kt

When claiming the profile it is not only necessary to update the metadata of the file but it is safe to also update the contents of the file to depict the current profile in the device.
One very nice example is:
1. User connects to **Account A** and backs up. (A **file_id_A** is created)
2. User disconnects from that account and connects to **Account B**.
3. The backup process will start again trying to backup to **file_id_A** wich will result in `404` and us deleting this id locally. The backup executor will retry without showing the error.
4. Upon retry since no file id exists, will end up in the `createBackupFile` which will create the profile in **B** with **file_id_B**
5. But the user decides to disconnect from **B**, same as (3) we will end up deleting `file_id_B` due to `404`.
6. …

Save contents while claiming

---

app/src/main/java/com/babylon/wallet/android/domain/RadixWalletException.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt

Depth of nested errors in this case is really getting out of hand. I did this change to not break anything else, but we should really simplify exceptions hierarchy at some point.
1. Trigger transaction that requires blind signing, validate that error message is shown

[ABW-3409] Properly display ledger errors which are cause of signing error

---

app/src/main/java/com/babylon/wallet/android/presentation/common/seedphrase/SeedPhraseInputDelegate.kt

1. Verify that seed phrase incorrect warning shows only when all input fields are non-empty

[ABW-3412] Update to seed phrase empty condition

---

app/src/main/java/com/babylon/wallet/android/domain/usecases/GetEntitiesWithSecurityPromptUseCase.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/GetSecurityProblemsUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/backup/BackupScreen.kt
app/src/test/java/com/babylon/wallet/android/domain/usecases/GetEntitiesWithSecurityPromptUseCaseTest.kt
app/src/test/java/com/babylon/wallet/android/fakes/FakePreferenceManager.kt
core/src/main/java/rdx/works/core/domain/cloudbackup/CloudBackupState.kt

This PR adds logic to not show backup warnings when a user has an updated manual backup file. See the `CloudBackupState` and the thread in slack.
1. Create a wallet and perform a cloud backup
2. Disabled cloud backup and do some updates in your profile
3. You will see backup warnings in the screens
4. Now export a manual backup file
5. You will not see any backup warnings **until you make a new change in your profile!**

Do not show warning when cloud backup is disabled and manual backup is updated

---

profile/src/main/java/rdx/works/profile/cloudbackup/CloudBackupSyncExecutor.kt

The solution came down to be pretty simple. When a job has been enqueued, but the worker has not decided to process it (due to the constraint not met (no network connection)), we start a timer that when finished will emit a backup error. If in the meantime the worker decides to dequeue the operation, then we cancel this timeout and rely on the worker's result.
1. Do a change on profile
2. Everything should work fine.
3. Set device to airplane mode.
4. Make a change to profile.
5. Wait a minute (literally)
6. The error is shown.
7. Still when you connect to internet, the worker will operate and still try to backup.
You can try the same until step 4, but then connect to internet without waiting a minute. You will not see any error (given the backup succeeded).

Show backup errors after significant period has passed since last enqueue.

---

app/src/main/java/com/babylon/wallet/android/presentation/main/MainViewModel.kt

This PR fixes unnecessary p2p link connection code being called whenever the profile is updated. This is not an issue as there is a guard check in the connector so the actual connection code is not executed again, but it's good to have this prevented at a higher lever anyway.

Fix p2p links observing

---

app/src/main/java/com/babylon/wallet/android/domain/usecases/GetEntitiesWithSecurityPromptUseCase.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/GetSecurityProblemsUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/backup/BackupScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/backup/BackupViewModel.kt
app/src/test/java/com/babylon/wallet/android/domain/usecases/GetEntitiesWithSecurityPromptUseCaseTest.kt
app/src/test/java/com/babylon/wallet/android/presentation/WalletViewModelTest.kt
core/src/main/java/rdx/works/core/domain/cloudbackup/BackupState.kt
profile/src/main/java/rdx/works/profile/domain/backup/GetBackupStateUseCase.kt

This PR decouples the cloud backup section from the manual backup state. In short, when a cloud backup is disabled or has any errors the warnings are yellow and they do not depend on the status of the manual backup, e.g. an updated manual backup file
1. Create wallet and turn on cloud backup. Do some changes in the profile.
2. Turn off cloud backup and do some changes in the profile.
3. Navigate to Backup screen and verify that the cloud backup section (status list) is yellow, and a warning would be presented at the top.
4. Perform a manual backup.
5. Verify that the warning at the top is gone and the status list is still yellow.

[ABW-3429] Decoupled warnings in cloud backup section of Backup screen

---

profile/src/main/java/rdx/works/profile/domain/backup/SaveTemporaryRestoringSnapshotUseCase.kt

This PR fixes re-link connector screen appearing after fresh install if there was an old system backup present with a profile containing p2p links.
1. Install app from 1.5.4 tag
2. Create or restore the profile and make sure there are p2p links
3. Perform a cloud backup (old system)
4. Uninstall the app
5. Install 1.6.0 version
6. Create profile
7. Verify that re-link connector screen is not appearing

Fix re-link connector screen appearing after fresh install

---

app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/seedphrases/SeedPhrasesScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/accountrecoveryscan/chooseseed/ChooseSeedPhraseScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/accountrecoveryscan/chooseseed/ChooseSeedPhraseViewModel.kt
profile/src/main/java/rdx/works/profile/domain/DeviceFactorSourceData.kt
profile/src/main/java/rdx/works/profile/domain/GetFactorSourcesWithAccountsUseCase.kt

- use all accounts for showing total count of accounts
- display Hidden accounts only box if seed phrase has only hidden ones
1. Verify counter displays all the accounts when hiding some
2. Verify that if all are hidden, it is marked under specific seed phrase

[ABW-3430] Display hidden accounts only state in seed phrases list item

---

app/src/main/java/com/babylon/wallet/android/domain/model/transaction/TransactionStatusParameterType.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/BuildDappResponseUseCase.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/transaction/CollectSignersSignaturesUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/transaction/TransactionStatusDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/transaction/TransactionStatusDialogNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/transaction/TransactionStatusDialogViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/submit/TransactionSubmitDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/Dialogs.kt
app/src/main/java/com/babylon/wallet/android/utils/AppEventBusImpl.kt
app/src/main/java/com/babylon/wallet/android/utils/StringExtensions.kt

- strip `origin` trailing slash so that proper signature is computed when handling login with challenge request
- pass flag to indicate that request is mobile connect in the transaction status dialogs

Update auth sign request to work with dapp

---

app/src/main/java/com/babylon/wallet/android/data/gateway/model/TokensAndLsusPricesResponse.kt

This PR fixes fiat price parsing by deserializing the price as Double. Now that Sargon truncates the decimals when overflowing, deserializing the price as Double won't be an issue. The issue now is when a price contains many decimals and deserializing it as String automatically applies the engineering notation, thus making Sargon fail when converting String (with engineering notation) to Decimal192. 
`"2.63376612877e-07".toDecimal192()` - this currently doesn't work, while using the Double extension works.

Fix fiat prices parsing

---

app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/backup/BackupViewModel.kt
profile/src/main/java/rdx/works/profile/cloudbackup/data/DriveClient.kt
profile/src/main/java/rdx/works/profile/cloudbackup/domain/CheckBackupStatusUseCase.kt
profile/src/main/java/rdx/works/profile/cloudbackup/domain/CheckCloudBackupFileAvailabilityUseCase.kt
profile/src/main/java/rdx/works/profile/domain/backup/GetBackupStateUseCase.kt
profile/src/test/java/rdx/works/profile/domain/GetBackupStateUseCaseTest.kt

In short, a "Last backup:" label is presented on the Backup screen when backup is disabled. This label indicates when was the last backup performed. 
Now, if the user keeps the backup disabled and revokes and/or delete the app data from Drive settings the wallet will still show the label on the screen which is misleading since no backup file on the cloud. 
Therefore, wallet must check the cloud backup file availability even when backup is disabled.
**Scenario 1**
1. Enable cloud backup in the wallet and perform a successful backup
2. Turn off the cloud backup and ensure that you see the "Last backup: ..." label
3. Navigate to the Google Drive settings and revoke or/and delete Radix Wallet app data
4. Relaunch the wallet and navigate to Backup screen. There you must see "**None**" in the …

[ABW-3434] Check cloud backup file availability when backup is disabled

---

app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferViewModel.kt

- use formatting that respect locale when applying max amount and filling it into text field
1. Before the fix, ensure you have asset with amount that is decimal number. Tap max amount in your default locale, then test it with locale that has different decimal separator then your default. For example in Polish locale decimal separator is coma, dot in UK locale.

Format decimal with respect to locale when max amount is tapped

---

app/src/main/java/com/babylon/wallet/android/presentation/status/dapp/DappInteractionDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/transaction/TransactionStatusDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/Dialogs.kt

Change indicator of mobile connect request (bottom copy to go back to browser) on status dialogs.
1. Run tx complete/tx failure, dapp interaction and verify that mobile connect "CTA" is updated

Update status dialogs indications of mobile connect requests

---

app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/derivepublickey/DerivePublicKeyDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/derivepublickey/DerivePublicKeyViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/createaccount/CreateAccountViewModel.kt

This PR fixes a bug where the user dismiss the bottom sheet dialog when creating a new account.
**This is very hard to reproduce.**
Test 1
1. With an existing wallet click on "Create a New Account" at wallet screen
2. At the "Create New Account" screen type an account name and click "Continue"
3. Dismiss the biometric prompt
4. Click on the "X" button of the "Creating Account" bottomsheet dialog
5. Remain at the "Create New Account" screen and select "Create with Ledger..."
6. Add a NEW ledger device
7. Once adding ledger flow is done select the new ledger and proceed
At this point the wallet returns again back to "Create New Account" screen. 
Test 2
1. Fresh install wallet
2. At "Create First Account" screen give a name and select with ledger
3. Click continue and authenticate
4. At …

Fix derive public key dialog when user dismiss

---

app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/mobileconnect/MobileConnectLinkViewModel.kt

This PR solves the following bug:
1. launch wallet
2. connect to a desktop dapp, e.g. https://dev-sandbox.rdx-works-main.extratools.works/
3. send a transaction request through webrtc fromt the above dapp - leave request on the screen
4. send a "Update Account Sharing" through webrtc fromt the above dapp
5. send a mobile connect request from RQ
6. send a mobile connect request from gumball
7. now you have a total of 4 requests in the queue
8. back to the wallet start rejecting requests one by one
At this point you won't get on the screen the last 2 (mobile) requests and you will dismiss only the first two.

Fix request handled on rejection at Login screen

---

app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/FeesResolver.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/TransactionAnalysisDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/AccountDepositSettingsProcessor.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/PoolContributionProcessor.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/PoolRedemptionProcessor.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/TransactionTypeExtensions.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/ValidatorClaimProcessor.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/ValidatorStakeProcessor.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/ValidatorUnstakeProcessor.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/AccountDepositSettingsTypeContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/DepositAccountContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/FeesSheet.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/GuaranteesSheet.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/PoolTypeContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/StakeTypeContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionAccountCard.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransactionAccountWithGuaranteesCard.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransferTypeContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/WithdrawAccountContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/guarantees/TransactionGuaranteesDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/model/AccountWithDepositSettingsChanges.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/model/AccountWithPredictedGuarantee.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/model/AccountWithTransferableResources.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/model/TransactionErrorMessage.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/submit/TransactionSubmitDelegate.kt
app/src/test/java/com/babylon/wallet/android/presentation/transaction/TransferableTests.kt

Move model classes under the `presentation/transaction/model/` package.

Restructure TransactionReviewViewModel

---

app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/selectpersona/SelectPersonaViewModel.kt

* When there is only one persona available, preselect it.
* When there are more than one personas or one persona was already authorised for a dApp continue the same logic as before
1. Create one persona. Subsequent logins with dApps have this persona pre-selected.
2. Create multiple personas. Subsequent logins have nothing preselected, except if one persona was authorised in the past. If so that persona in ordered first, preselected and displays the last used timestamp

Pre-select single persona when none selected

---

app/src/main/java/com/babylon/wallet/android/data/repository/tokenprice/FiatPriceRepository.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/GetEntitiesWithSecurityPromptUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/AccountScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/AccountTopBar.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/AccountViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/AccountCardView.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt
app/src/test/java/com/babylon/wallet/android/presentation/WalletViewModelTest.kt

* The wallet screen refreshes the assets every 5 minutes and the account screen every 1 minute
* The "refresh timer" starts counting from the last time a previous refresh occurred. Meaning that if the user does a manual refresh meanwhile then the timer restarts.
* Errors are not shown when an automatic refresh occurs.
* Substantial changes to the `WalletViewModel` regarding the structure of state and how it is represented. More detailed types for refresh and price state exist and give more flexibility to preserve state and convey it to the user.
1. Open wallet from scratch
2. Reopen wallet
3. Play around with refresh
4. Do the same with account screen

Automatic refresh

---

app/src/main/java/com/babylon/wallet/android/presentation/main/MainViewModel.kt

This PR fixes p2p links connection re-establishing after factory reset.
1. Add a p2p link
2. Troubleshooting -> Factory reset
3. Create a new wallet or restore one
4. Make sure the p2p links are connected

Fix p2p links not being reconnected after wallet reset

---

app/src/main/java/com/babylon/wallet/android/data/repository/dapps/WellKnownDAppDefinitionRepository.kt
app/src/main/java/com/babylon/wallet/android/data/repository/networkinfo/NetworkInfoRepository.kt
app/src/main/java/com/babylon/wallet/android/di/ApplicationModule.kt
app/src/main/java/com/babylon/wallet/android/di/HttpModule.kt
app/src/main/java/com/babylon/wallet/android/di/NetworkApiModule.kt

* Required headers are also included to the previously named "SimpleHttpClient"
* Renamed the annotations to depict the state of the client
* Moved the appropriate providers to http module
* Separated `BaseUrlInterceptor` with `HeaderInterceptor` since the first one is only used in dynamic gateway apis.

Add missing headers to all http clients that need it

---

app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/SimpleAccountCard.kt

* Long display names were pushing the address to the end of the row.
1. Rename an account using a long name
2. Check the account settings and see that the name does not push the address far to the end.

Fix long names issue for accounts in SimpleAccountCard

---

app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/selectpersona/SelectPersonaScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/selectpersona/SelectPersonaViewModel.kt
app/src/test/java/com/babylon/wallet/android/presentation/dapp/selectpersona/SelectPersonaViewModelTest.kt

This PR adds to the #1029. The logic for pre-selecting a persona will be:
* Preselect the first one if none is selected.
* Be sure to sort the personas based on the last used timestamp if some of them were authorised by the dApp in the past.
* If a new persona is created, select that.
That way the user doesn't have to do an extra click while logging in to a dApp.

Preselect the newly created persona

---

app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/importlegacywallet/ImportLegacyWalletScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/accounts/ChooseAccountSheet.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/AddLinkConnectorScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/NumberedValuesList.kt

* We have 3 occasions the QR code scanner is invoked.
1. When linking a connector extension
2. When importing from legacy wallet.
3. When scanning for account address in assets transfer.
* Some paddings and alignments changed.
* Specifically for connector extension linking some instructions were added at the bottom  
1. Try linking a connector extension, either from settings or when trying to add a ledger device when there is no CE connected yet.
2. Try the transfer flow and click on the QR icon when trying to type an account address.
3. Try opening the legacy wallet scanner

Implement ui changes for all QR code scanners

---

app/src/main/java/com/babylon/wallet/android/data/gateway/survey/NPSSurveyApi.kt
app/src/main/java/com/babylon/wallet/android/data/repository/NPSSurveyRepository.kt
app/src/main/java/com/babylon/wallet/android/presentation/survey/NPSSurveyViewModel.kt

For testing, you should check that NPS event is received in our refiner project (dev/prod) and that `nps` score is an Int, by visiting `Reporting Dashboards` tab and checking if submitted score contributes to report. In case of dismissing the dialog, only `id` and `form_uuid` should be sent. 
In case of assistance needed in accessing the dashboard, let me know

Use body instead of query params when submitting NPS survey

---

app/src/main/java/com/babylon/wallet/android/presentation/status/dapp/DappInteractionDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/dapp/DappInteractionDialogViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/transaction/TransactionStatusDialogViewModel.kt

[Jira Ticket](https://radixdlt.atlassian.net/browse/ABW-3504)
This PR fixes both transaction success and dapp interaction success sheets' dismisal behavior.
1. Launch a request from a dApp (doesn't matter if mobile or desktop)
2. Complete the transaction in the wallet but don't dismiss the success/failure sheet
3. Launch another request from a dApp
4. Check that the previous transaction success/failure sheet is dismissed and the new incoming request is displayed

[ABW-3504 ] - Fix transaction and status success sheets dismissal behavior

---

app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/AccountDepositSettingsTypeContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/submit/TransactionSubmitDelegate.kt

Align depositors/resources icon sections on tx preview screen.
1. Preview tx that changes both resource rule and depositor and verify icons are centered.

[ABW-3579] Align depositors/resources icon section

---

app/src/main/java/com/babylon/wallet/android/data/repository/homecards/HomeCardsObserverWrapper.kt
app/src/main/java/com/babylon/wallet/android/data/repository/homecards/HomeCardsRepository.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/DeleteWalletUseCase.kt

This PR fixes the issue of unnecessarily displaying the home cards after factory resetting the wallet and creating a new one.
1. Create a new wallet
2. Make sure the link connector home card is displayed
3. Troubleshooting -> Factory reset
4. Restore a backup
5. Make sure there are no home cards displayed

Clear home cards state when resetting wallet

---

app/src/main/java/com/babylon/wallet/android/presentation/navigation/NavigationHost.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/TargetAccountCard.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/assets/SpendingAssetItem.kt

* Each so called "spending asset" can be clicked and display its details with the already existing Asset Dialog.
* The clickable area for NFTs is the whole box, but for fungibles it is only the icon and the text since the rest is the area that needs to focus the text field.
* In order to invoke the dialog we need to also pass the `fromAccount.address` which is the account these assets belong to and are being prepared to transfer somewhere else.
1. Do a transfer with multiple assets, fungibles, NFTs, LSUs, Pool Units and claims.
2. Click on them
3. The amount displayed in the dialog for fungibles, is the owned amount the from account owns.
<video src="https://github.com/radixdlt/babylon-wallet-android/assets/125959264/54b29bbe-ecb3-4e07-a517-befb865392b3">

Show Asset Details from transfer screen

---

app/src/main/java/com/babylon/wallet/android/domain/RadixWalletException.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/ResolveNotaryAndSignersUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/model/TransactionErrorMessage.kt

- if we don't find signers in a profile - we run tx through gateway anyway. 
1. Follow the thread [here](https://rdxworks.slack.com/archives/C05V4202J90/p1720906856387759?thread_ts=1720795701.179099&cid=C05V4202J90) and use two previews provided by users to test the bug.
2. First manifest is creating advanced account controlled by a badge and depositing some XRD into it. To make preview work, replace account in 1st and last instruction with account you control, and add empty tuple to value marked as an error - using manifest editor on the left pane.
3. Write down created entities.
4. Open 2nd manifest, modify account in 1st and last instruction to be the one you control. Use created badge address as resource address in 1st instruction. Use created advanced account address as account …

Don't fail transaction preview when signers are not found in profile 

---

app/src/main/java/com/babylon/wallet/android/data/repository/tokenprice/FiatPriceRepository.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt

When testing locally on testnet in debug builds Umair noticed that the prices were not identical when moving from account screen to wallet screen. This is due to 2 reasons:
1. We need to request for fresh fiat data when the wallet screen starts, even when it comes to foreground. So in order to always be up to date, we request for new data `onStart` instead on ViewModel's `init`.
2. The testnet cache was invalidated between screens since a new instance was always being injected, so the amounts were shown completely different. 
1. One change is to simply make the testnet repository a singleton. This will maintain the cache of random "fake" fiat values for better and easier design testing.
2. The price fluctuation was made smaller so to "replicate" real price fluctuations happening on real …

Make testnet fiat repository singleton

---

app/src/main/java/com/babylon/wallet/android/WalletApp.kt
app/src/main/java/com/babylon/wallet/android/data/dapp/LedgerMessenger.kt
app/src/main/java/com/babylon/wallet/android/di/UiModule.kt
app/src/main/java/com/babylon/wallet/android/domain/RadixWalletException.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/GetFreeXrdUseCase.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/NotariseTransactionUseCase.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/SignTransactionUseCase.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/transaction/CollectSignersSignaturesUseCase.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/transaction/SignWithDeviceFactorSourceUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/AccessFactorSourceProxyContract.kt
app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/AccessFactorSourcesProxyImpl.kt
app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/deriveaccounts/DeriveAccountsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/derivepublickey/DerivePublicKeyViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/signatures/GetSignaturesDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/signatures/GetSignaturesNavGraph.kt
app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/signatures/GetSignaturesViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/createaccount/CreateAccountViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/settings/AccountSettingsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/navigation/NavigationHost.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/createpersona/CreatePersonaViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/submit/TransactionSubmitDelegate.kt
app/src/main/java/com/babylon/wallet/android/utils/AppEventBusImpl.kt
app/src/test/java/com/babylon/wallet/android/mockdata/Profile.kt
app/src/test/java/com/babylon/wallet/android/presentation/GetSignaturesViewModelTest.kt
app/src/test/java/com/babylon/wallet/android/presentation/status/address/AddressDetailsDialogViewModelTest.kt
app/src/test/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModelTest.kt
app/src/test/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModelTestExperimental.kt
app/src/test/java/com/babylon/wallet/android/presentation/transaction/vectors/TransactionReviewViewModelTestExtensions.kt

This PR is a continuation of the Access Factor Sources refactor. The purpose of this refactor is to create a module that every time it accesses the factor sources:
- it can be called from different places e.g. when signing transaction or creating entity and it takes an input
- when it is called then a bottom sheet dialog is being presented as long as wallet accessing the factor sources
- when accessing is done, it returns the **minimum** output to the caller (for example a public key in case of creating an account, not the whole account!)
--input--> [access-factor-source-dialog] --output-->
This PR fixes the transaction signing process. In short:
- adds a new method in the file `AccessFactorSourcesProxyContract` to `getSignatures` when signing
- adds a new `GetSignaturesDialog` and its …

[ABW-2747] Refactor signature request in transactions

---

app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletScreen.kt

This PR fixes the issue of the accounts not being loaded when opening the app.
1. Force close the app if it's in the apps stack
2. Open the app
3. Verify that the loading state is properly centered and the accounts are displayed

Fix wallet accounts loading issue

---

app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/ExpandableText.kt

* The metadata view when rendering an `ExpandableText` like a string metadata, was flickering on occasion when displayed in asset details dialog (which is a bottom sheet)
* Also observed previously in @giannis-rdx PR for #1030 when an animate modifier is used with `BottomSheetDialogWrapper` does not work properly.
1. Check the video on the ticket to see the problem
2. Notify me to send you such NFT with such metadata or you can create an NFT with a custom string metadata with more than 2 lines of text.

Fix flicker issue in metadata view

---

app/src/main/java/com/babylon/wallet/android/presentation/account/AccountViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/TroubleshootingSettingsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt

* When an error is occurred the first time we try to resolve assets and no fiat values are yet received we need to show an error in the fiat value too. This was not handled in both wallet and account screen.
* Disabled Olympia recovery in debug builds. If you try to recover olympia accounts while you are on stokenet, you will import "mainnet" accounts while in stokenet. This will result in an error from GW. This is why this bug was surfaced.
1. Try to force an error while opening the app with no prior cache. You can maybe do that by importing an old wallet, or importing Umair's wallet that has mainnet accounts in stokenet.
2. See that the fiat value displays as error instead of shimerring.

Fix fiat value on error

---

app/src/main/java/com/babylon/wallet/android/presentation/account/AccountViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/assets/AssetsChooserDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/AssetsView.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/NFTsTab.kt

* NFTs list was relying on triggering NFTs page when the index of the shimmering view was the the same as the current collections' size. So that used to mean that when the user scrolls to the bottom, the next page was received.
* In the current bug, since the account refresh was requested, the items were invalidated, making the collection having 0 items. So in order for the next page to be triggered, the user should scroll back to the first item.
* Clearly this logic was wrong. Now whenever a shimmering view is appeared, meaning that we lack of needed data to display the NFT collection, we need to request for the next nfts page. We should also mark this specific collection as pending so, multiple renders to the list do not cause the request to be triggered constantly.
1. Add an NFT …

Fix NFTs pages request after account refresh

---

app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt

* Even though the code was disabling fiat value, did not move the for loop since it used a simple `break` thus ending up enabling again the fiat prices with empty values.

Fix hiding fiat value in release stokenet

---

app/src/main/java/com/babylon/wallet/android/data/gateway/extensions/StateEntityDetailsApiHelper.kt
app/src/main/java/com/babylon/wallet/android/data/repository/state/AccountsStateCache.kt

* When opening transaction review, we need to fetch XRD information for all our accounts that can pay for fees. We need to do that as quick as possible.
* When vault information for XRD is cached we can directly look at the vault on GW.
* But when none such info exists, we need to fetch entity details for the account and find the XRD amount. This is a bit more slow but the only alternative when the wallet hasn't yet fetched any prior information about XRD.
* This PR fixes the method in `AccountsStateCache` to take care of this case and also introduces a simple method on api that fetches any amount information for accounts for a specific resource address. Please look at the documentation for more details.

Fetch XRD amount when vault info is not available

---

app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt

* When in release mode on stokenet, since fiat prices need to be disabled, after the wallet is refreshed, the spinner needs to hide.

Fix spinner not hiding when disabling fiat prices

---

app/src/main/java/com/babylon/wallet/android/presentation/model/DisplaySubtitle.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/assets/AssetDialog.kt
core/src/main/java/rdx/works/core/domain/resources/Resource.kt

The name should be displayed as is when rendered in asset details metadata and account screen. When displayed as title in AssetDetails dialog or everywhere else, we keep the same logic as before

Avoid NFT name truncation when displayed in account or asset details

---

app/build.gradle
app/src/main/java/com/babylon/wallet/android/presentation/status/dapp/DappInteractionDialogViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/transaction/TransactionStatusDialogViewModel.kt

This PR updates the transaction status screen dismissal behavior.
1. Launch a transfer and keep staying on the Review Transaction screen
2. Launch a gumball transfer
3. Launch a gumball account sharing transaction
4. Complete the transfer launched from the app
5. Verify that after the transaction is completed the next one is immediately displayed and the success screen is not shown
6. Verify the same for the next transaction
7. Verify that if there are no pending transactions in the queue, the success screen is shown
https://github.com/user-attachments/assets/fc2762d7-2aa8-4245-bd47-a895191a049e

Update transaction status screen dismissal behavior

---

app/src/main/java/com/babylon/wallet/android/presentation/status/transaction/TransactionStatusDialogViewModel.kt

When there is a blocking transaction like 3rd party deposits account change, after the transaction completes, display the X button.

Show close button when a blocking transaction completed

---

app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/selectpersona/SelectPersonaScreen.kt

Based on current Zeplin screen.
- Subtitle dApp name in bold is achieved by crowdin strings update, not part of this PR
Waiting for empty state
| Before | After |
| -------- | ------- |
| <img src="https://github.com/user-attachments/assets/6fd264b1-f38c-4556-8483-f260fc1663cc">  | <img src="https://github.com/user-attachments/assets/73da91f7-c62a-488d-b61f-879e4716d2b1">  |

Persona selection UI adjustments

---

app/src/main/java/com/babylon/wallet/android/data/repository/state/StateRepository.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/assets/CacheNewlyCreatedEntitiesUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/assets/nonfungible/NonFungibleAssetDialogContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/TransactionAnalysisDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/GeneralTransferProcessor.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/PoolContributionProcessor.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/PoolRedemptionProcessor.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/TransactionTypeExtensions.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/TransferProcessor.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/ValidatorClaimProcessor.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/ValidatorStakeProcessor.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/ValidatorUnstakeProcessor.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/PoolTypeContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/StakeTypeContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/TransferTypeContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/Thumbnail.kt
app/src/test/java/com/babylon/wallet/android/domain/usecases/SearchFeePayersUseCaseTest.kt
app/src/test/java/com/babylon/wallet/android/fakes/StateRepositoryFake.kt
app/src/test/java/com/babylon/wallet/android/presentation/dapp/login/DAppAuthorizedLoginViewModelTest.kt

- cache NFT items that are newly created for an EXISTING NFT collection. 
Given the structure of our transaction analysis, this solution seemed easiest. I'm open for a suggestions to improve it.
1. See ticket description for a slack thread describing how issue manifests itself.

[ABW-3653] Cache newly created NFT items for existing resource

---

app/src/main/java/com/babylon/wallet/android/presentation/account/settings/specificassets/SpecificAssetsDepositsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/account/AccountSelectionCard.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/backup/RestoreFromBackupScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/accountrecoveryscan/chooseseed/ChooseSeedPhraseScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/FeePayerSelectionContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/LedgerListItem.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/RadixRadioButton.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/card/PersonaCard.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/persona/PersonaDetailCard.kt

This PR updates all the radio buttons in the app to match the design.

Update radio buttons

---

app/src/main/java/com/babylon/wallet/android/domain/RadixWalletException.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/AuthorizeSpecifiedPersonaUseCase.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/RespondToIncomingRequestUseCase.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/VerifyDAppUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/login/DAppUnauthorizedLoginViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/status/transaction/TransactionStatusDialogViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/submit/TransactionSubmitDelegate.kt
app/src/test/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModelTest.kt

This PR aims to help us troubleshoot weird dApp validation error that Radquest users have seen. By always sending dApp response we are able to get CE logs and see reason of the failure. 
- always respond to dapp if we fail to verify request
- add additional information to `messsage` field
- log non fatal to crashlytics, as a backup mean
1. I tested it with emulator, simulating very weak network. Before that change we didn't respond to dApp in case of network related failures.

Improve error handling when verifying dApp request

---

app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/personadetail/PersonaDetailViewModel.kt

- when app is left on persona details when transaction comes in and is signed - app crashes on status dialog
This is caused by listening for transaction status in that particular screen, and it's filter clause used `lateinit` variable that is not initialized
1. Open app on persona details screen - the one where we have button to create auth key.
2. Send any transaction from a dApp (sandbox/dashboard) and sign transaction
3. App crashes before the fix

[ABW-3669] Make uploadAuthKeyInteractionId nullable

---

app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/createpersona/CreatePersonaNav.kt

Crash hapened when user was on persona confirmation screen, popping screen to get back to the flow that started persona creation. Stacktrace says that current screen when crash occured is persona selection in dapp request handling flow. I was not able to reproduce, but it is clear from the report that it happened at `getBackStackEntry(ROUTE_CREATE_PERSONA)` which throws if route is not on the backstack. Wrapped calls to `getBackStackEntry` in runCatching, and if we can't find root screen of the flow for some reason (entry == null), just pop current screen.
1. I tried regular persona creation flow in dApp request handling - couldn't reproduce
2. While being at persona creation confirmation screen, moved app to the background, simulated process death with `adb shell am kill <package_name>` …

Fix crash when popping persona creation flow.

---

app/src/main/java/com/babylon/wallet/android/data/dapp/model/DappToWalletInteractionExtensions.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/AuthorizeSpecifiedPersonaUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginViewModel.kt

Re-arranged how we determine starting screen for request handling. Now it is as follow, when we hit one of those conditions, we don't examine the rest (when clause):
- if there is ongoing accounts request that is not reset and we didn't grant account access to this type of request for the dapp - we start with account permission screen
- if there is ongoing persona data request that is not reset and we didn't grant data access to this type of request for the dapp - we start with ongoing persona data screen
- if there is one time accounts request - start with chosing account screen for one time data
- if there is one time persona data request - start with persona data one time screen
If none of the above are met, we have a request with either ongoing account and (or) persona data and we …

Update dapp request handling logic to properly determine starting screen

---

app/src/main/java/com/babylon/wallet/android/presentation/account/AccountNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/createaccount/CreateAccountNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/history/HistoryNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/settings/AccountSettingsNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/settings/devsettings/DevSettingsNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/main/MainScreenNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/cloudbackup/ConnectCloudBackupNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/eula/EulaNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/backup/RestoreFromBackupNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/withoutbackup/RestoreWithoutBackupNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/SettingsNavGraph.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/createpersona/CreatePersonaNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/createpersona/CreatePersonaScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/personadetail/PersonaDetailNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/personaedit/PersonaEditNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/SecurityCenterNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/accountrecoveryscan/scan/AccountRecoveryScanNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/persona/AddFieldSheet.kt

[Jira Ticket](https://radixdlt.atlassian.net/browse/ABW-3654)
This PR updates navigation transitions between screens.

[ABW-3654] - Update screens navigation transitions

---

app/src/main/java/com/babylon/wallet/android/data/transaction/ROLAClient.kt
app/src/main/java/com/babylon/wallet/android/domain/model/signing/SignPurpose.kt
app/src/main/java/com/babylon/wallet/android/domain/model/signing/SignType.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/BuildDappResponseUseCase.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/signing/SignTransactionUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/AccessFactorSourceProxyContract.kt
app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/signatures/GetSignaturesDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/signatures/GetSignaturesViewModel.kt
app/src/test/java/com/babylon/wallet/android/presentation/GetSignaturesViewModelTest.kt

So far wallet has been signing transaction and auth requests with `transactionSigning` instance.
This PR fixes this issue.

Pick the right factor instance based on sign purpose

---

app/src/main/java/com/babylon/wallet/android/presentation/transfer/accounts/ChooseAccountSheet.kt

[Jira Ticket](https://radixdlt.atlassian.net/browse/ABW-3679)
This PR hides "Or: Choose one of your own Accounts” text when there are no accounts to choose from in transfer flow.
1. Account -> Transfer
2. Add a transfer for each suggested account (if there are others)
3. Verify that "Or: Choose one of your own Accounts” text is not shown when there are no accounts to choose from

[ABW-3679] - Hide own accounts text when there are no other accounts

---

app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonic/AddSingleMnemonicScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsScreen.kt

[Jira Ticket](https://radixdlt.atlassian.net/browse/ABW-3710)
This PR attempts to fix the issue when the seed phrase entry screen is cut out at the bottom (most likely because of unnecessary ime padding). The fix relies on using exactly the same code as in `RestoreMnemonicScreen` where the issue doesn't occur.
1. Go to Wallet Settings -> Troubleshooting -> Account recovery scan -> seed phrase entry
2. Go back and forth and check that the seed phrase entry screen is not cut out

[ABW-3710] - Fix seed phrase entry screen issue

---

app/src/main/java/com/babylon/wallet/android/presentation/settings/approveddapps/dappdetail/DappDetailScreen.kt

- visibility of disconnect button was tied to accounts shared with that persona. If they were empty - button was not shown, which is clearly wrong.
1. Share some persona data with a dApp, then go to dapp details -> persona sheet - observe "Disconnect" button is not shown before this fix.

[ABW-3708] Update persona detail sheet on dapp detail screen

---

app/src/main/java/com/babylon/wallet/android/presentation/navigation/NavigationHost.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/SecurityCenterNav.kt

[Jira Ticket](https://radixdlt.atlassian.net/browse/ABW-3709)
This PR fixes transition animations between the content inside `RestoreMnemonicScreen` as well as the transition between the `RestoreMnemonicScreen` and the next screen. Additionally, fixed the primary button loading after the biometric prompt is canceled by the user. 
> Note: The transition between different Entities content inside `RestoreMnemonicScreen` cannot be seen due to the current implementation limitations: the transition being based on AnimatedVisibility composable
Verify transition animations within restore mnemonic screen

[ABW-3709] - Fix restore mnemonic transition animations

---

app/src/main/java/com/babylon/wallet/android/presentation/dialogs/dapp/DAppDetailsDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/dialogs/dapp/DAppDetailsDialogViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/approveddapps/dappdetail/DappDetailScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/approveddapps/dappdetail/DappDetailViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/PersonasScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/DappDetails.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/card/PersonaCard.kt
app/src/test/java/com/babylon/wallet/android/presentation/settings/authorizeddapps/ApprovedDappsViewModelTest.kt
app/src/test/java/com/babylon/wallet/android/presentation/settings/dappdetail/DappDetailViewModelTest.kt

- reuse same UI for dapp details screen and dapp details dialog accessible from persona details.
Since this is `dialog` destination, it's not respecting edge to edge - I think we have similar issue with other dialogs that use `dialog`. This can't be fix easily without changing dialog to be part of the screen, unless I'm missing something here
1. Verify that details opened by " personas -> persona detail -> dApp click " are the same as the one opened in from "Approved Dapps" screen. Verify that forget this dapp removes dApp from the persona and dismisses dialog.

[ABW-3678] Reuse same view for dApp details screen and dApp details dialog

---

app/src/main/java/com/babylon/wallet/android/presentation/dialogs/address/AddressDetailsDialog.kt

left image: device account 
right  image: ledger account (dialog is scrolled all the way to the bottom)
1. Open a ledger account and verify there space between the two buttons at the bottom of the dialog

[ABW-2698] Add space between buttons in account card

---

app/src/main/java/com/babylon/wallet/android/presentation/account/composable/FiltersDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/accounts/ChooseAccountSheet.kt
app/src/main/java/com/babylon/wallet/android/presentation/transfer/assets/ChooseAssetsSheet.kt

- asset chooser - transfer
- account chooser - transfer
- filters dialog on history screen
This problem was result of recent padding updates I did, sheets listed above declared specific insets values to adjust for `navigationBarsPadding()` that was used in the sheet themselves.
1. Before the fix UI either overlaps with navigation bar or padding is too big (history filters dialog)

Update sheets insets

---

app/src/main/java/com/babylon/wallet/android/domain/usecases/GetDAppWithResourcesUseCase.kt
app/src/main/java/com/babylon/wallet/android/domain/usecases/ResolveComponentAddressesUseCase.kt
core/src/main/java/rdx/works/core/domain/resources/metadata/StandardMetadata.kt

- for dApps resolution in tx review - check if dapp links back to the component
- for dApp resources - validate if resource lists dApp address in `dapp_definitions` and filter out those that do not
Additional context can be found in the ticket [here](https://radixdlt.atlassian.net/browse/ABW-3707?atlOrigin=eyJpIjoiNTYwYzUwMDE5YWJiNDEzYThjMGY1ZGY3NzlkMWYwODIiLCJwIjoiaiJ9)
1. For first case I can't give specific transaction to test this - I was tampering with the data in debug mode to reproduce situation when component is unknown
2. For second case - connect with Radquest, and see there are 14 resources listed before the fix, after the fix there are only 12 of them, as 2 of them do not link back to Radquest dApp

[ABW-3707] Verify 2 way link for dapp resources/dapps in tx review

---

app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/signatures/GetSignaturesDialog.kt

Align text in get signatures dialog

---

app/src/main/java/com/babylon/wallet/android/MainActivity.kt
designsystem/src/main/java/com/babylon/wallet/android/designsystem/theme/RadixColors.kt

- we still have a glitch when switching theme while app is in the foreground with this update, but otherwise it works consistently using same colors in light/dark theme for navigation bar

Configure navigation bar style to be always light

---

app/src/main/java/com/babylon/wallet/android/presentation/dialogs/assets/fungible/FungibleDialogContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/dialogs/assets/lsu/LSUDialogContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/dialogs/assets/pool/PoolUnitDialogContent.kt

This PR adds `divisibility` for fungible resources in fungible detail view.
if the `divisibility` we do not show the row.
1. open fungible detail view
2. verify the divisibility is there

[ABW-2699] Add divisibility for fungible resources

---

app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/FeesSheet.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/NetworkFeeContent.kt

This PR adds functionality to warn users about paying fees with an account not involved in transaction
1. Execute a transfer or another transaction 
2. Add as fee payer an account that is not involved in the transaction
3. You must see a warning (see video)
https://github.com/user-attachments/assets/5cc32efb-0440-4af8-9229-007d3b28aa44

[ABW-3721] Warning for not involved accounts in transactions

---

app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/seedphrases/confirm/ConfirmMnemonicNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/seedphrases/confirm/ConfirmMnemonicScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/seedphrases/reveal/RevealSeedPhraseScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/seedphrases/reveal/RevealSeedPhraseViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/SeedPhraseInputVerificationForm.kt
designsystem/src/main/java/com/babylon/wallet/android/designsystem/composable/MnemonicWordTextField.kt

[Ticket](https://radixdlt.atlassian.net/browse/ABW-3749)
This PR fixes the crash when tapping "I have written down this seed phrase" from Reveal seed phrase screen.
Additionally cleaned up the unused code and fixed a screen transition animation.
1. Open Security Factors -> Seed Phrases -> Reveal Seed Phrase
2. Tap back and choose "I have written down this seed phrase"
3. Verify the app doesn't crash

[ABW-3749] - Fix mnemonic confirmation crash

---

app/src/main/java/com/babylon/wallet/android/WalletApp.kt
app/src/main/java/com/babylon/wallet/android/presentation/dialogs/lock/AppLockScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dialogs/lock/AppLockViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/main/MainViewModel.kt
app/src/main/java/com/babylon/wallet/android/utils/AppEventBusImpl.kt
app/src/main/java/com/babylon/wallet/android/utils/DeviceCapabilityHelper.kt
app/src/test/java/com/babylon/wallet/android/presentation/CreatePersonaViewModelTest.kt
app/src/test/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModelTest.kt

See [this](https://rdxworks.slack.com/archives/C03Q8QK1GLW/p1724672451342089) message for buggy behavior. Expected behavior:
- when user has advanced lock on and remove lock screen on the device, opening wallet results in a lock screen with not secure dialog shown. After going to settings and coming back to wallet, user can tap padlock icon and unlock the wallet. No Secure Dialog warning on wallet home screen
- when advanced lock is off, app should behave as it was before. So if user disable device lock screen and open Wallet, dialog is there. After going to settings and re-enabling lock, opening the wallet from recent - dialog is gone.
1. See above

Properly handle not secure dialog when advanced lock is turned on

---

core/src/main/java/rdx/works/core/domain/Decimal192.kt

This PR fixes the crash caused by formatting some asset prices:
`java.lang.NumberFormatException: For input string: "13.859522 M"`

Fix crash when formatting assets fiat value

---

app/src/main/java/com/babylon/wallet/android/data/repository/cache/database/StateDao.kt
app/src/main/java/com/babylon/wallet/android/data/repository/state/AccountsStateCache.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/preferences/assetshiding/HiddenAssetsViewModel.kt

[Jira Ticket](https://radixdlt.atlassian.net/browse/ABW-3786)
This PR fixes hidden pool units not being shown in "Hidden Assets" screen.
Check [this](https://rdxworks.slack.com/archives/C03Q8QK1GLW/p1725882586529139) for a test profile.
1. Restore a profile with some hidden pool units
2. Go to hidden assets screem
3. Verify that the hidden pool units are displayed

[ABW-3786] - Fix hidden pool units not showing

---

app/src/main/java/com/babylon/wallet/android/domain/RadixWalletException.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/TransactionAnalysisDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/model/TransactionErrorMessage.kt

[Jira Ticket](https://radixdlt.atlassian.net/browse/ABW-3751)
This PR updates transaction failure handling (when the preview receipt has failed) by presenting the generic error pop-up with a user-friendly message and dismissing the transaction review screen when the pop-up is cancelled.
1. Connect to stokenet gumball
2. Factory reset wallet
3. Create a new wallet
4. Launch a transaction from stokenet gumball
5. Check that the error pop-up shows and the screen is dismissed when cancelled

[ABW-3751] - Update transaction preview failure handling

---

app/src/main/java/com/babylon/wallet/android/presentation/account/composable/EmptyResourcesContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/dialogs/assets/AssetDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/approveddapps/ApprovedDappsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/PersonasScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/createpersona/CreatePersonaInfoScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/personas/createpersona/CreatePersonaScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/preferences/depositguarantees/DepositGuaranteesScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/preferences/gateways/GatewaysScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/FeesSheet.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/GuaranteesSheet.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/AddLinkConnectorScreen.kt

This PR replaces the info strings with new ones and adds a missing info button for Customize Guarantees bottom sheet. It also updates its UI based on Zeplin screens.

Replace info strings

---

app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/TransactionAnalysisDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt

Double-checked the app behavior when receiving invalid manifest requests while investigating tickets:
[ABW-3794](https://radixdlt.atlassian.net/browse/ABW-3794)
[ABW-3792](https://radixdlt.atlassian.net/browse/ABW-3792)
[ABW-3795](https://radixdlt.atlassian.net/browse/ABW-3795)
The crash reported in the tickets was previously fixed during the Account Lockers feature implementation.
This PR improves error handling for transaction manifest errors by displaying the generic error pop-up which also dismisses the transaction review screen when acknowledged by the user.
Also, fixed unnecessary calls for the account lockers status check when resuming `WalletScreen`, it's required only when the user explicitly pulls to refresh.
[ABW-3794]: …

Improve error handling for transaction manifest errors

---

app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/derivepublickey/DerivePublicKeyDialog.kt
app/src/main/java/com/babylon/wallet/android/presentation/accessfactorsources/derivepublickey/DerivePublicKeyViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/createaccount/CreateAccountScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/settings/AccountSettingsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/mnemonics/RestoreMnemonicsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/preferences/entityhiding/HiddenEntitiesScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/troubleshooting/reset/FactoryResetViewModel.kt

This PR fixes a few small UI issues:
- [ABW-3788](https://radixdlt.atlassian.net/browse/ABW-3788) Animation flicker when hiding an account
- The keyboard was unnecessarily showing after tapping Continue when creating the first account
- The `DerivePublicKey` was briefly shown after providing biometrics when creating the first account
- The keyboard was unnecessarily showing after tapping Continue on Seed Phrase entering screen during onboarding
- When resetting the wallet, the Security Center status on Factory Reset screen unnecessarily turned yellow (warning state)
- The bottom of the list on Hidden Personas & Accounts was too close to the bottom of the screen
[ABW-3788]: https://radixdlt.atlassian.net/browse/ABW-3788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …

Fix small UI issues

---

app/src/main/java/com/babylon/wallet/android/presentation/account/settings/AccountSettingsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/settings/AccountSettingsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/linkedconnectors/LinkedConnectorsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/linkedconnectors/LinkedConnectorsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/preferences/gateways/GatewaysScreen.kt
designsystem/src/main/java/com/babylon/wallet/android/designsystem/composable/RadixTextField.kt

This PR adds functionality to rename link connectors.
Also minor update in Gateways screen based on zeplin screens.
1. Navigate to Linked Connectors screen
2. Edit a link connector by clicking on the pen icon
➡️  Ensure that link connection has not been affected (e.g. terminated or restarted)
https://github.com/user-attachments/assets/47f61a86-a700-41c6-84b3-94b775c0d197

[ABW-3268] Rename link connector

---

app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/wallet/WalletViewModel.kt

This PR fixes the account prompts (hide) of the Wallet screen in case the locker claim 
- succeeds 
- fails because a recover has happened in the meantime 
1. Airdrop something to your account 
2. Claim it from the wallet screen (click on the account prompt)
➡️ Assert that after the claim (successful transaction) the prompt is gone (it might take 1-2 seconds)
1. Airdrop something to your account
2. At the wallet screen pull to refresh to see the prompt in the corresponding account
3. Now at this point recover back what you airdropped
4. At the wallet screen do not pull to refresh and click on the prompt 
5. You will get an error dialog. Click on this and the app returns back to the Wallet screen
➡️ Assert the prompt is gone

[ABW-3833, ABW-3834] Fix account locker prompts when locker claim succeeds or fails

---

.github/workflows/pr_and_main.yml

Since babylon wallet now depends on `sargon-desktop-bins` that include linux binaries, all the runners that used to run on Mac os can change to ubuntu.

Change remaining mac os runners to ubuntu

---

app/src/main/java/com/babylon/wallet/android/domain/usecases/BuildDappResponseUseCase.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/login/DAppUnauthorizedLoginViewModel.kt

If the user hasn't provided the seed phrase for the associated accounts/personas while restoring from backup, when logging in a dapp we should display the same error message as in other similar cases in the wallet.
1. Perform logins with personas or accounts with our stokenet dapps, while the seed phrase is missing.

Accounts personas seed phrase missing dialog

---

app/src/main/java/com/babylon/wallet/android/data/gateway/extensions/EntityMetadataCollectionExtensions.kt
app/src/main/java/com/babylon/wallet/android/data/repository/cache/database/StateDatabase.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/composable/AssetMetadataRow.kt
app/src/main/java/com/babylon/wallet/android/presentation/account/composable/MetadataView.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/processor/TransactionTypeExtensions.kt
core/src/main/java/rdx/works/core/domain/DApp.kt
core/src/main/java/rdx/works/core/domain/resources/metadata/Metadata.kt
core/src/main/java/rdx/works/core/domain/resources/metadata/StandardMetadata.kt

In the previous versions we allowed dApp definitions to set the `claimed_websites` metadata as `Url`, `UrlArray`, `Origin` and `OriginArray`. This PR makes the definition of `claimed_websites` more strict that verifies dApps that define their claimed websites as `Origin` or `OriginArray`.
In order to allow that, 
1. `MetadataType.Origin` domain type was created and origin metadata are mapped to this type
2. In 2-way link verification we query the claimed websites as origin and not just url.
3. Url and Origin are both rendered the same in UI.
4. DB should migrate in order to force the cache to refresh.
1. Try to login to many dapps with dev mode off. If you try to login to dev-sandbox, it should not allow you to validate it. (Although this may vary according to what dapp definition is set. …

Force check origin metadata on dapp validation

---

app/src/main/java/com/babylon/wallet/android/presentation/onboarding/restore/backup/RestoreFromBackupScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/backup/BackupScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/Dialogs.kt
core/src/main/java/rdx/works/core/serializers/StringBase64EncodedSerializer.kt
core/src/main/java/rdx/works/core/serializers/StringUrlEncodedSerializer.kt
profile/src/main/java/rdx/works/profile/domain/backup/BackupType.kt

This PR solves a problem reported by users when importing a profile with password. The culprit was that special characters could not be used when passed as input in our nav system. A base64 encoding is used in combination with kotlinx serialization.
This PR also solves 3 more UI bugs related to profile export/import with password:
1. When exporting the profile with password, the textfields had no space between them.
2. Used `BottomSheetDialogWrapper` in `BackupScreen` that allows text field context actions such as paste, which is valuable to a user that might want to paste a password. 
3. Did the same in `RestoreFromBackupScreen`
1. Create passwords with special characters
4. Export and import the profile.
5. Try to use copy-paste functionality to also test the change to the bottom sheets

Special characters in profile import

---

app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/FeesSheet.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/NetworkFeeContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/fees/TransactionFees.kt
app/src/test/java/com/babylon/wallet/android/presentation/transaction/FeesResolverTest.kt

This PR fixes an issue where the wallet show a negative total fee when the fees are fully paid by the dapp.
In short:
- `TransactionsFee` calculates the total fee in two different places. At the one the calculation is correct but the other that was used to display and into the transaction was wrong.
- Added unit test to cover the case of fees paid by dapp.
- Some fixes for the warnings in the review screen to take into account the case where the total fee is zero.
1. Send the following transaction to the wallet
```
CALL_METHOD Address("YOUR_ACCOUNT_ADDRESS") "create_proof_of_amount" Address("resource_tdx_2_1tknxxxxxxxxxradxrdxxxxxxxxx009923554798xxxxxxxxxtfd2jc") Decimal("11");
POP_FROM_AUTH_ZONE Proof("proof");
CALL_METHOD Address("component_tdx_2_1cr2vmx64gjsq3jf38va9q8hfw6sfta97hclevpay …
```

[ABW-3880] Fix transaction fee when fully paid by dapp

---

app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/summary/manifest/ManifestSummaryExtensions.kt

[ABW-3929](https://radixdlt.atlassian.net/browse/ABW-3929)
[Thread](https://rdxworks.slack.com/archives/C03Q8QK1GLW/p1731330628453889)
This PR fixes pre-auth tx displaying as complex and unnecessarily displaying more NFTs than required for the transaction.
[ABW-3929]: https://radixdlt.atlassian.net/browse/ABW-3929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ABW-3929] - Fix pre-auth tx displaying as complex

---

app/src/main/java/com/babylon/wallet/android/presentation/dialogs/assets/AssetDialogNav.kt

This PR fixes the issue when the details of a newly created NFT were indefinitely loading on the details screen opened from the transaction review.
1. Launch a create NFTs tx from sandbox
2. Tap on an NFT item
3. Make sure there is no loading state for the NFT details like current supply or behaviors

Fix newly created NFT details

---

app/src/main/java/com/babylon/wallet/android/presentation/transfer/TransferViewModel.kt

This PR solves a bug reported: When a user selects multiple NFTs to transfer, but tries to unselect one, the whole collection gets unselected.
1. Open Transfer screen.
2. Select Multiple NFTs to transfer in the same collection
3. Unselect one
4. Only the one you unselected should be unchecked.

Fix NFT unselect

---

app/src/main/java/com/babylon/wallet/android/data/dapp/IncomingRequestRepository.kt
app/src/main/java/com/babylon/wallet/android/presentation/dialogs/transaction/TransactionStatusDialogViewModel.kt

In short, we `markRequestAsHandled` in `TransactionStatusDialogViewModel` which makes sense because this is the last step of the transaction lifecycle, but this doesn't always work as expected.
:warning:  Before explaining the issues an important note to keep in mind:
For each transaction status we create a new `TransactionStatusDialog`. So when we start with "completing" status then we navigate to `TransactionStatusDialog` with "success" status (or "fail").
Therefore each of this dialogs have their own instances of `TransactionStatusDialogViewModel`
**The issues are two**:
1. we `markRequestAsHandled` at
- `onDismiss` :white_check_mark: (it is the dismiss status dialog)
- TransactionStatus: Success :white_check_mark:
- TransactionStatus: Fail :x: This is missing! The request of course …

Fix request handling

---

app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginViewModel.kt

This PR updates validation of account addresses and persona address when proof of ownership is present.
1. From the test sandbox dapp send a request with an account request item and a proof of ownership with empty account addresses. It should reject the request.
2. Then send a request with an account request item and proof of ownership with an empty persona address. It should reject the request.

Reject request when empty addresses in proof of ownership

---

app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/account/ChooseAccountsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/account/ChooseAccountsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/selectpersona/SelectPersonaScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/selectpersona/SelectPersonaViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/verifyentities/VerifyEntitiesViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/verifyentities/accounts/VerifyAccountsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/verifyentities/persona/VerifyPersonaScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/accountonetime/OneTimeChooseAccountsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/accountonetime/OneTimeChooseAccountsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/unauthorized/login/DAppUnauthorizedLoginViewModel.kt

Before the [refactoring](https://github.com/radixdlt/babylon-wallet-android/pull/1216) every authorization operation was executed in `DAppAuthorizedLoginViewModel` and `DAppUnauthorizedLoginViewModel` thus the error handling.
After the refactoring authorization has been moved to each request item screen. This PR handles the missing error handling when authorization fails. Sadly the screens have to call again the `DAppAuthorizedLoginViewModel` or `DAppUnauthorizedLoginViewModel` to handle errors. This has to be improved when we work on the login screens.
1. Sign an authorized request with an entity in recovery required state and you should see an error dialog.

Fix handling of authorization errors in login flows

---

app/src/main/java/com/babylon/wallet/android/domain/RadixWalletException.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/TransactionReviewViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/analysis/TransactionAnalysisDelegate.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/submit/TransactionSubmitDelegate.kt

* When analysis fails, when responding back to dApp the message of the throwable, or the message of the cause of the throwable, is communicated back to CE.
* The manifest modification regarding assertions was incorrectly placing the predicted and not the calculated guaranteed amount to the assertion.

Fixes on responding to dApp and assertions

---

app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/login/DAppAuthorizedLoginViewModel.kt

This PR fixes response to dapp when account proof is requested after first login.
Before the fix wallet failed to send to the dapp the account(s) proof when this was requested again after the first login. In order to understand the bug, do the following:
1. if sandbox is in approved dapps, then forget it.
2. From sandbox connect to the wallet including proofs in persona and accounts request. 
3. Once connected, then logout from sandbox.
4. Connect again. You will notice that dapp fais to connect.
Try again with the fix.

Send account proof when challenge exists in account request item

---

app/src/main/java/com/babylon/wallet/android/presentation/common/securityshields/ConfirmationDelay.kt
app/src/main/java/com/babylon/wallet/android/presentation/common/securityshields/OrView.kt
app/src/main/java/com/babylon/wallet/android/presentation/common/securityshields/SecurityShieldsCommonComposables.kt
app/src/main/java/com/babylon/wallet/android/presentation/common/securityshields/ThresholdDisplay.kt
app/src/main/java/com/babylon/wallet/android/presentation/dapp/authorized/verifyentities/VerifyEntitiesContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityshields/SecurityShieldsNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityshields/SecurityShieldsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityshields/shielddetails/SecurityShieldDetailsNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityshields/shielddetails/SecurityShieldDetailsScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/settings/securitycenter/securityshields/shielddetails/SecurityShieldDetailsViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/transaction/composables/SecurifyEntityTypeContent.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/AssetsCommonViews.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/NFTsTab.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/PoolUnitsTab.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/StakingTab.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/TokensTab.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/card/CommonCard.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/card/PersonaCard.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/model/securityshields/SecurityShieldCard.kt
designsystem/src/main/java/com/babylon/wallet/android/designsystem/composable/RadixTextButton.kt

This PR solves adds the Security Shield details screen. (read commit messages for more details).
This PR is on top of this [PR](https://github.com/radixdlt/babylon-wallet-android/pull/1334). So you can apply a shield and test the details screen.
Future tasks (**NOT** for this PR):
- rename shield functionality
- edit factors functionality
- security shield status functionality
1. Build shields and navigate to details screen
[here](https://rdxworks.slack.com/archives/C03Q8QK1GLW/p1740414917985659)

[ABW-4084] Add security shield details screen

---

app/build.gradle
app/src/main/java/com/babylon/wallet/android/AppLockStateProvider.kt
app/src/main/java/com/babylon/wallet/android/WalletApp.kt
app/src/main/java/com/babylon/wallet/android/presentation/main/MainScreen.kt
app/src/main/java/com/babylon/wallet/android/presentation/main/MainScreenNav.kt
app/src/main/java/com/babylon/wallet/android/presentation/main/MainViewModel.kt
app/src/main/java/com/babylon/wallet/android/presentation/navigation/NavigationHost.kt
app/src/main/java/com/babylon/wallet/android/presentation/ui/composables/assets/PoolUnitsTab.kt

Additional fixes attached on the release branch:
1. Fixed advanced lock mechanism. The initial value is read only when the application starts and not each time an activity is subscribed to it. If the `MainActivity` is killed and restored again by the system then the lock screen would appear again. Also changed to initial value to be unlocked (i.e. when in onboarding, the app should be unlocked since there is no profile)
2. Pass down to `MainScreen` and `WalletScreen` the view model reference (`MainViewModel`) instead of the `State<MainViewModel.State>` which forced the screen to redraw and the nav host to lose its state when the app state changed.
3. Fix a UI bug in Pool Units were the separator between resources in a pool was not centered correctly.

Release 1.12.0
